before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - deploy_staging_datevrij_nl
  - deploy_staging_liefdesdate_nl
  - deploy_staging_sweetalk_nl
  - deploy_production_datevrij_nl
  - deploy_production_liefdesdate_nl
  - deploy_production_sweetalk_nl

deploy_staging_datevrij_nl:
  stage: deploy_staging_datevrij_nl
  environment:
    name: staging
  script:
    -
      git fetch &&
      git checkout staging &&
      git pull origin staging &&
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan optimize &&
      php artisan queue:restart &&
      exit"
  only:
    - staging

deploy_staging_liefdesdate_nl:
  stage: deploy_staging_liefdesdate_nl
  environment:
    name: staging
  script:
    - 
      git fetch &&
      git checkout staging &&
      git pull origin staging &&
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan optimize &&
      php artisan queue:restart &&
      exit"
  only:
    - staging

deploy_staging_sweetalk_nl:
  stage: deploy_staging_sweetalk_nl
  environment:
    name: staging
  script:
    - 
      git fetch &&
      git checkout staging &&
      git pull origin staging &&
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan optimize &&
      php artisan queue:restart &&
      exit"
  only:
    - staging

deploy_production_datevrij_nl:
  stage: deploy_production_datevrij_nl
  environment:
    name: production
  script:
    - 
      git fetch &&
      git checkout master &&
      git pull origin master &&
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan optimize &&
      php artisan queue:restart &&
      exit"
  only:
    - master

deploy_production_liefdesdate_nl:
  stage: deploy_production_liefdesdate_nl
  environment:
    name: production
  script:
    - 
      git fetch &&
      git checkout master &&
      git pull origin master &&
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan optimize &&
      php artisan queue:restart &&
      exit"
  only:
    - master

deploy_production_sweetalk_nl:
  stage: deploy_production_sweetalk_nl
  environment:
    name: production
  script:
    - 
      git fetch &&
      git checkout master &&
      git pull origin master &&
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan optimize &&
      php artisan queue:restart &&
      exit"
  only:
    - master