<?php namespace App\Helpers\ApplicationConstants;

/**
 * Class UserConstants
 * @package App\Helpers\ApplicationConstants
 */
class UserConstants
{
    public static $maxAmountOnline = 30;

    public static $ageGroups = [
        '18-25' => '18-25',
        '26-35' => '26-35',
        '36-45' => '36-45',
        '46+' => '46+'
    ];

    public static $radiuses = [
        '20',
        '50',
        '80',
    ];

    public static function getAgeGroups() {
        return self::$ageGroups;
    }

    public static function getRadiuses() {
        return self::$radiuses;
    }


    /**
     * @return int
     */
    public static function getMaxAmountOnline()
    {
        return self::$maxAmountOnline;
    }


    public static $userTableFields = [
        'common' => [
            'public' => [
                'username',
                'first_name',
                'last_name',
                'postal_code',
                'street_name'
            ],
            'private' => [
                'password',
                'account_type',
                'active'
            ],
        ],
        'peasant' => [
            'public' => [
                'email'
            ]
        ]
    ];

    public static $selectableFields = [
        'common' => [
            'public' => [
                'gender' => [
                    1 => 'male',
                    2 => 'female'
                ],
                'looking_for_gender' => [
                    1 => 'male',
                    2 => 'female'
                ],
                'relationship_status' => [
                    1 => 'single',
                    2 => 'in_a_relationship',
                    3 => 'complicated'
                ],
                'body_type' => [
                    1 => 'slender',
                    2 => 'average',
                    3 => 'athletic',
                    4 => 'curvy',
                    5 => 'big'
                ],
                'height' => [
                    1 => '<140',
                    2 => '140-150',
                    3 => '150-160',
                    4 => '160-170',
                    5 => '170-180',
                    6 => '180-190',
                    7 => '190-200',
                    8 => '>200'
                ],
                'eye_color' => [
                    1 => 'green',
                    2 => 'blue',
                    3 => 'brown',
                    4 => 'hazel',
                    5 => 'black'
                ],
                'hair_color' => [
                    1 => 'black',
                    2 => 'grey',
                    3 => 'white',
                    4 => 'brown',
                    5 => 'blond',
                    6 => 'dark_blond',
                    7 => 'red',
                    8 => 'pink'
                ],
                'smoking_habits' => [
                    1 => 'regular',
                    2 => 'social',
                    3 => 'none'
                ],
                'drinking_habits' => [
                    1 => 'regular',
                    2 => 'social',
                    3 => 'none'
                ]
            ],
            'private' => [
                'role' => [
                    1 => 'admin',
                    2 => 'peasant',
                    3 => 'bot',
                    4 => 'operator',
                    5 => 'editor'
                ],
                'account_type' => [
                    1 => 'free',
                    2 => 'small',
                    3 => 'medium',
                    4 => 'large',
                ]
            ]
        ],
        'bot' => [
            'private' => [
                'category' => [
                    1 => 'seniors',
                    2 => 'teens',
                    3 => 'naked',
                    4 => 'dressed',
                ]
            ],
        ]
    ];

    public static $textFields = [
        'common' => [
            'public' => [
                'about_me'
            ]
        ]
    ];

    public static $textInputs = [
        'common' => [
            'public' => [
                'dob',
                'city',
                'country'
            ],
            'private' => [
                'lat',
                'lng'
            ]
        ]
    ];

    public static $immutableFields = [
        'gender'
    ];

    public static $cities = [
        'nl' => [
            "'s-Graveland (NL)",
            "'s-Gravendeel (NL)",
            "'s-Gravenpolder (NL)",
            "'s-Gravenzande (NL)",
            "'s-Heer-Hendrikskinderen (NL)",
            "'s-Heerenhoek (NL)",
            "'s-Hertogenbosch (NL)",
            "'s Gravenmoer (NL)",
            "'t Harde (NL)",
            "'t Kabel (NL)",
            "'t Zand (NL)",
            "Aagtekerke (NL)",
            "Aalburg (NL)",
            "Aalden (NL)",
            "Aalsmeer (NL)",
            "Aalsmeerderbrug (NL)",
            "Aalst (NL)",
            "Aalten (NL)",
            "Aardenburg (NL)",
            "Abbekerk (NL)",
            "Abbenes (NL)",
            "Abcoude (NL)",
            "Achterberg (NL)",
            "Achterveld (NL)",
            "Achthuizen (NL)",
            "Achtmaal (NL)",
            "Aduard (NL)",
            "Aerdenhout (NL)",
            "Aerdt (NL)",
            "Afferden (NL)",
            "Akersloot (NL)",
            "Akkrum (NL)",
            "Albergen (NL)",
            "Alblasserdam (NL)",
            "Alde Leie (NL)",
            "Alem (NL)",
            "Alkmaar (NL)",
            "Almelo (NL)",
            "Almere (NL)",
            "Almere Haven (NL)",
            "Almkerk (NL)",
            "Alphen (NL)",
            "Alphen aan den Rijn (NL)",
            "Ameide (NL)",
            "America (NL)",
            "Amerongen (NL)",
            "Amersfoort (NL)",
            "Ammerstol (NL)",
            "Ammerzoden (NL)",
            "Amstelhoek (NL)",
            "Amstelveen (NL)",
            "Amstenrade (NL)",
            "Amsterdam (NL)",
            "Anderen (NL)",
            "Andijk (NL)",
            "Ane (NL)",
            "Angeren (NL)",
            "Anjum (NL)",
            "Ankeveen (NL)",
            "Anloo (NL)",
            "Anna Paulowna (NL)",
            "Annen (NL)",
            "Apeldoorn (NL)",
            "Appelscha (NL)",
            "Appeltern (NL)",
            "Appingedam (NL)",
            "Arcen (NL)",
            "Arkel (NL)",
            "Arnemuiden (NL)",
            "Arnhem (NL)",
            "Asperen (NL)",
            "Assen (NL)",
            "Assendelft (NL)",
            "Asten (NL)",
            "Augustinusga (NL)",
            "Avenhorn (NL)",
            "Axel (NL)",
            "Baambrugge (NL)",
            "Baarland (NL)",
            "Baarle-Nassau (NL)",
            "Baarlo (NL)",
            "Baarn (NL)",
            "Baars (NL)",
            "Babberich (NL)",
            "Badhoevedorp (NL)",
            "Baexem (NL)",
            "Bakel (NL)",
            "Baken (NL)",
            "Bakhuizen (NL)",
            "Balgoij (NL)",
            "Balk (NL)",
            "Ballum (NL)",
            "Banholt (NL)",
            "Barchem (NL)",
            "Barendrecht (NL)",
            "Barneveld (NL)",
            "Batenburg (NL)",
            "Bathmen (NL)",
            "Bavel (NL)",
            "Bedum (NL)",
            "Beegden (NL)",
            "Beek (NL)",
            "Beek (NL)",
            "Beek (NL)",
            "Beekbergen (NL)",
            "Beerta (NL)",
            "Beerzerveld (NL)",
            "Beesd (NL)",
            "Beesel (NL)",
            "Beets (NL)",
            "Beetsterzwaag (NL)",
            "Beilen (NL)",
            "Beinsdorp (NL)",
            "Belfeld (NL)",
            "Bellingwolde (NL)",
            "Bemelen (NL)",
            "Bemmel (NL)",
            "Beneden-Leeuwen (NL)",
            "Bennebroek (NL)",
            "Bennekom (NL)",
            "Benningbroek (NL)",
            "Benthuizen (NL)",
            "Berg (NL)",
            "Bergambacht (NL)",
            "Bergeijk (NL)",
            "Bergen (NL)",
            "Bergen (NL)",
            "Berg en Dal (NL)",
            "Bergen op Zoom (NL)",
            "Bergentheim (NL)",
            "Bergharen (NL)",
            "Berghem (NL)",
            "Bergschenhoek (NL)",
            "Beringe (NL)",
            "Berkenwoude (NL)",
            "Berkhout (NL)",
            "Berlicum (NL)",
            "Best (NL)",
            "Beugen (NL)",
            "Beuningen (NL)",
            "Beusichem (NL)",
            "Beverwijk (NL)",
            "Biddinghuizen (NL)",
            "Bierum (NL)",
            "Biervliet (NL)",
            "Biest (NL)",
            "Bilthoven (NL)",
            "Bitgum (NL)",
            "Bladel (NL)",
            "Blaricum (NL)",
            "Bleiswijk (NL)",
            "Blerick (NL)",
            "Bleskensgraaf (NL)",
            "Blitterswijck (NL)",
            "Bloemendaal (NL)",
            "Blokker (NL)",
            "Blokzijl (NL)",
            "Bocholtz (NL)",
            "Bodegraven (NL)",
            "Boeicop (NL)",
            "Boekel (NL)",
            "Boelenslaan (NL)",
            "Boerakker (NL)",
            "Boesingheliede (NL)",
            "Bolsward (NL)",
            "Borculo (NL)",
            "Borger (NL)",
            "Born (NL)",
            "Borne (NL)",
            "Borsele (NL)",
            "Bosch en Duin (NL)",
            "Boskoop (NL)",
            "Bosschenhoofd (NL)",
            "Bourtange (NL)",
            "Boven-Hardinxveld (NL)",
            "Boven-Leeuwen (NL)",
            "Bovenkarspel (NL)",
            "Bovensmilde (NL)",
            "Boxmeer (NL)",
            "Boxtel (NL)",
            "Brakel (NL)",
            "Breda (NL)",
            "Bredevoort (NL)",
            "Breezand (NL)",
            "Breskens (NL)",
            "Breugel (NL)",
            "Breukelen (NL)",
            "Breukeleveen (NL)",
            "Brielle (NL)",
            "Briltil (NL)",
            "Britsum (NL)",
            "Broekhin (NL)",
            "Broekhuizen (NL)",
            "Broek in Waterland (NL)",
            "Broek op Langedijk (NL)",
            "Brouwershaven (NL)",
            "Bruchem (NL)",
            "Brucht (NL)",
            "Bruinisse (NL)",
            "Brummen (NL)",
            "Brunssum (NL)",
            "Buchten (NL)",
            "Budel (NL)",
            "Budel-Dorplein (NL)",
            "Budel-Schoot (NL)",
            "Buinerveen (NL)",
            "Buitenkaag (NL)",
            "Buitenpost (NL)",
            "Bunde (NL)",
            "Bunnik (NL)",
            "Bunschoten (NL)",
            "Buren (NL)",
            "Buren (NL)",
            "Burgerveen (NL)",
            "Burgum (NL)",
            "Burgwerd (NL)",
            "Burum (NL)",
            "Bussum (NL)",
            "Buurse (NL)",
            "Cadier en Keer (NL)",
            "Cadzand (NL)",
            "Callantsoog (NL)",
            "Capelle aan den IJssel (NL)",
            "Castricum (NL)",
            "Centrum (NL)",
            "Chaam (NL)",
            "Clinge (NL)",
            "Coevorden (NL)",
            "Colijnsplaat (NL)",
            "Colmschate (NL)",
            "Craailo (NL)",
            "Cromvoirt (NL)",
            "Cruquius (NL)",
            "Cuijk (NL)",
            "Culemborg (NL)",
            "Daarle (NL)",
            "Dalen (NL)",
            "Dalfsen (NL)",
            "Damwald (NL)",
            "De Bilt (NL)",
            "De Blesse (NL)",
            "De Cocksdorp (NL)",
            "Dedemsvaart (NL)",
            "Deest (NL)",
            "De Falom (NL)",
            "De Glind (NL)",
            "De Goorn (NL)",
            "De Hoef (NL)",
            "De Horst (NL)",
            "De Klomp (NL)",
            "De Koog (NL)",
            "De Kwakel (NL)",
            "Delden (NL)",
            "Delden (NL)",
            "Delfgauw (NL)",
            "Delft (NL)",
            "Delfzijl (NL)",
            "De Lier (NL)",
            "De Lutte (NL)",
            "De Meern (NL)",
            "De Moer (NL)",
            "Den Bommel (NL)",
            "Den Bosch (NL)",
            "Den Burg (NL)",
            "Den Deijl (NL)",
            "Den Dolder (NL)",
            "Den Dungen (NL)",
            "Denekamp (NL)",
            "Den Haag (NL)",
            "Den Helder (NL)",
            "Den Hoorn (NL)",
            "Den Hout (NL)",
            "Den Ilp (NL)",
            "Den Oever (NL)",
            "De Punt (NL)",
            "De Rijp (NL)",
            "De Steeg (NL)",
            "Deurne (NL)",
            "Deventer (NL)",
            "De Waal (NL)",
            "De Westereen (NL)",
            "De Wijk (NL)",
            "De Wilp (NL)",
            "De Zilk (NL)",
            "Didam (NL)",
            "Diemen (NL)",
            "Diepenheim (NL)",
            "Diepenveen (NL)",
            "Dieren (NL)",
            "Diessen (NL)",
            "Dieteren (NL)",
            "Diever (NL)",
            "Dijk (NL)",
            "Dinteloord (NL)",
            "Dinxperlo (NL)",
            "Dirkshorn (NL)",
            "Dirksland (NL)",
            "Dodewaard (NL)",
            "Doenrade (NL)",
            "Doesburg (NL)",
            "Doetinchem (NL)",
            "Dokkum (NL)",
            "Domburg (NL)",
            "Dongen (NL)",
            "Doorn (NL)",
            "Doornenburg (NL)",
            "Doornspijk (NL)",
            "Doorwerth (NL)",
            "Dordrecht (NL)",
            "Dorp (NL)",
            "Dorst (NL)",
            "Drachten (NL)",
            "Drempt (NL)",
            "Dreumel (NL)",
            "Driebergen (NL)",
            "Driebruggen (NL)",
            "Driehuis (NL)",
            "Driel (NL)",
            "Driemond (NL)",
            "Drogeham (NL)",
            "Dronryp (NL)",
            "Dronten (NL)",
            "Drunen (NL)",
            "Druten (NL)",
            "Duin (NL)",
            "Duiven (NL)",
            "Duivendrecht (NL)",
            "Dwingeloo (NL)",
            "Earnewald (NL)",
            "Echt (NL)",
            "Echten (NL)",
            "Echtenerbrug (NL)",
            "Eckart (NL)",
            "Edam (NL)",
            "Ede (NL)",
            "Ederveen (NL)",
            "Eede (NL)",
            "Eefde (NL)",
            "Eelde-Paterswolde (NL)",
            "Eelderwolde (NL)",
            "Eemnes (NL)",
            "Eenrum (NL)",
            "Eerbeek (NL)",
            "Eersel (NL)",
            "Eethen (NL)",
            "Eext (NL)",
            "Eexterzandvoort (NL)",
            "Egchel (NL)",
            "Egmond-Binnen (NL)",
            "Egmond aan Zee (NL)",
            "Eibergen (NL)",
            "Eijsden (NL)",
            "Eindhoven (NL)",
            "Einighausen (NL)",
            "Elburg (NL)",
            "Ell (NL)",
            "Ellecom (NL)",
            "Elsendorp (NL)",
            "Elsloo (NL)",
            "Elst (NL)",
            "Elst (NL)",
            "Emmeloord (NL)",
            "Emmen (NL)",
            "Emmer-Compascuum (NL)",
            "Emst (NL)",
            "Engelen (NL)",
            "Enkhuizen (NL)",
            "Ens (NL)",
            "Enschede (NL)",
            "Enschot (NL)",
            "Enspijk (NL)",
            "Enter (NL)",
            "Enumatil (NL)",
            "Epe (NL)",
            "Epen (NL)",
            "Epse (NL)",
            "Erica (NL)",
            "Erichem (NL)",
            "Erm (NL)",
            "Ermelo (NL)",
            "Erp (NL)",
            "Escharen (NL)",
            "Espel (NL)",
            "Etten (NL)",
            "Everdingen (NL)",
            "Ewijk (NL)",
            "Exloo (NL)",
            "Eygelshoven (NL)",
            "Eys (NL)",
            "Ezinge (NL)",
            "Farmsum (NL)",
            "Feanwalden (NL)",
            "Ferwert (NL)",
            "Fijnaart (NL)",
            "Finsterwolde (NL)",
            "Fleringen (NL)",
            "Fluitenberg (NL)",
            "Flushing (NL)",
            "Foxhol (NL)",
            "Franeker (NL)",
            "Frederiksoord (NL)",
            "Gaanderen (NL)",
            "Galder (NL)",
            "Gameren (NL)",
            "Gapinge (NL)",
            "Garderen (NL)",
            "Garmerwolde (NL)",
            "Garsthuizen (NL)",
            "Garyp (NL)",
            "Gasselte (NL)",
            "Gasselternijveen (NL)",
            "Geertruidenberg (NL)",
            "Geervliet (NL)",
            "Gees (NL)",
            "Geesteren (NL)",
            "Geesteren (NL)",
            "Geldermalsen (NL)",
            "Geldrop (NL)",
            "Geleen (NL)",
            "Gelselaar (NL)",
            "Gemeente Rotterdam (NL)",
            "Gemert (NL)",
            "Gemonde (NL)",
            "Genderen (NL)",
            "Gendringen (NL)",
            "Gendt (NL)",
            "Genemuiden (NL)",
            "Gennep (NL)",
            "Giesbeek (NL)",
            "Giessenburg (NL)",
            "Giessendam (NL)",
            "Gieten (NL)",
            "Gieterveen (NL)",
            "Giethoorn (NL)",
            "Gilze (NL)",
            "Glimmen (NL)",
            "Goes (NL)",
            "Goirle (NL)",
            "Goor (NL)",
            "Gorinchem (NL)",
            "Gorredijk (NL)",
            "Gorssel (NL)",
            "Gouda (NL)",
            "Gouderak (NL)",
            "Goudswaard (NL)",
            "Goutum (NL)",
            "Gramsbergen (NL)",
            "Grashoek (NL)",
            "Grathem (NL)",
            "Grave (NL)",
            "Greup (NL)",
            "Grijpskerk (NL)",
            "Groeningen (NL)",
            "Groenlo (NL)",
            "Groenveld (NL)",
            "Groesbeek (NL)",
            "Groessen (NL)",
            "Groet (NL)",
            "Groningen (NL)",
            "Gronsveld (NL)",
            "Groot-Agelo (NL)",
            "Groot-Ammers (NL)",
            "Grootebroek (NL)",
            "Grootegast (NL)",
            "Grou (NL)",
            "Grubbenvorst (NL)",
            "Gulpen (NL)",
            "Guttecoven (NL)",
            "Gytsjerk (NL)",
            "Haaften (NL)",
            "Haaksbergen (NL)",
            "Haalderen (NL)",
            "Haamstede (NL)",
            "Haaren (NL)",
            "Haarle (NL)",
            "Haarlem (NL)",
            "Haarlemmerliede (NL)",
            "Haelen (NL)",
            "Halfweg (NL)",
            "Halle (NL)",
            "Hallum (NL)",
            "Halsteren (NL)",
            "Hank (NL)",
            "Hantum (NL)",
            "Hantumhuizen (NL)",
            "Hapert (NL)",
            "Haps (NL)",
            "Hardenberg (NL)",
            "Harderwijk (NL)",
            "Haren (NL)",
            "Haren (NL)",
            "Harich (NL)",
            "Harkema (NL)",
            "Harkstede (NL)",
            "Harlingen (NL)",
            "Harmelen (NL)",
            "Hartwerd (NL)",
            "Hasselt (NL)",
            "Hattem (NL)",
            "Haule (NL)",
            "Haulerwijk (NL)",
            "Hauwert (NL)",
            "Havelte (NL)",
            "Hazerswoude-Dorp (NL)",
            "Hazerswoude-Rijndijk (NL)",
            "Hedel (NL)",
            "Hedel (NL)",
            "Heeg (NL)",
            "Heelsum (NL)",
            "Heemskerk (NL)",
            "Heemstede (NL)",
            "Heenvliet (NL)",
            "Heerde (NL)",
            "Heerenveen (NL)",
            "Heerhugowaard (NL)",
            "Heerjansdam (NL)",
            "Heerle (NL)",
            "Heerlen (NL)",
            "Heesch (NL)",
            "Heeswijk (NL)",
            "Heeswijk-Dinther (NL)",
            "Heeten (NL)",
            "Heeze (NL)",
            "Heijen (NL)",
            "Heijningen (NL)",
            "Heikant (NL)",
            "Heilig Landstichting (NL)",
            "Heiloo (NL)",
            "Heinenoord (NL)",
            "Heino (NL)",
            "Hekelingen (NL)",
            "Helden (NL)",
            "Helenaveen (NL)",
            "Hellendoorn (NL)",
            "Hellevoetsluis (NL)",
            "Hellouw (NL)",
            "Helmond (NL)",
            "Helvoirt (NL)",
            "Hem (NL)",
            "Hemelum (NL)",
            "Hendrik-Ido-Ambacht (NL)",
            "Hengelo (NL)",
            "Hengelo (NL)",
            "Hengevelde (NL)",
            "Hennaard (NL)",
            "Hensbroek (NL)",
            "Herbaijum (NL)",
            "Herkenbosch (NL)",
            "Herkingen (NL)",
            "Hernen (NL)",
            "Herpen (NL)",
            "Herten (NL)",
            "Herveld (NL)",
            "Herwijnen (NL)",
            "Heteren (NL)",
            "Heukelum (NL)",
            "Heusden (NL)",
            "Heveadorp (NL)",
            "Heythuysen (NL)",
            "Hierden (NL)",
            "Hijken (NL)",
            "Hillegom (NL)",
            "Hilvarenbeek (NL)",
            "Hilversum (NL)",
            "Hindeloopen (NL)",
            "Hippolytushoef (NL)",
            "Hoedekenskerke (NL)",
            "Hoek (NL)",
            "Hoek van Holland (NL)",
            "Hoenderloo (NL)",
            "Hoensbroek (NL)",
            "Hoevelaken (NL)",
            "Hoge Donk (NL)",
            "Hollandsche Rading (NL)",
            "Hollandscheveld (NL)",
            "Hollum (NL)",
            "Holten (NL)",
            "Holthees (NL)",
            "Holthone (NL)",
            "Holtum (NL)",
            "Holwierde (NL)",
            "Homoet (NL)",
            "Honselersdijk (NL)",
            "Hoofddorp (NL)",
            "Hoofdplaat (NL)",
            "Hoogblokland (NL)",
            "Hoogeloon (NL)",
            "Hoogerheide (NL)",
            "Hoogersmilde (NL)",
            "Hoogeveen (NL)",
            "Hoogezand (NL)",
            "Hooge Zwaluwe (NL)",
            "Hooghalen (NL)",
            "Hoogkarspel (NL)",
            "Hoogkerk (NL)",
            "Hoogland (NL)",
            "Hooglanderveen (NL)",
            "Hoogmade (NL)",
            "Hoogvliet (NL)",
            "Hoogwoud (NL)",
            "Hoorn (NL)",
            "Hoorn (NL)",
            "Hoornaar (NL)",
            "Horn (NL)",
            "Horst (NL)",
            "Hout (NL)",
            "Houtakker (NL)",
            "Houten (NL)",
            "Huijbergen (NL)",
            "Huissen (NL)",
            "Huis ter Heide (NL)",
            "Huizen (NL)",
            "Hulsberg (NL)",
            "Hulshorst (NL)",
            "Hulst (NL)",
            "Hummelo (NL)",
            "Hurdegaryp (NL)",
            "IJhorst (NL)",
            "IJlst (NL)",
            "IJmuiden (NL)",
            "IJsselmuiden (NL)",
            "IJsselstein (NL)",
            "IJzendijke (NL)",
            "IJzendoorn (NL)",
            "Ilpendam (NL)",
            "Ingelum (NL)",
            "Ingen (NL)",
            "Ittervoort (NL)",
            "Jabeek (NL)",
            "Jisp (NL)",
            "Joppe (NL)",
            "Joure (NL)",
            "Jubbega (NL)",
            "Julianadorp (NL)",
            "Jutrijp (NL)",
            "Kaag (NL)",
            "Kaatsheuvel (NL)",
            "Kalenberg (NL)",
            "Kamerik (NL)",
            "Kampen (NL)",
            "Kamperland (NL)",
            "Kantens (NL)",
            "Kapelle (NL)",
            "Kats (NL)",
            "Katwijk (NL)",
            "Katwijk aan Zee (NL)",
            "Katwoude (NL)",
            "Keijenborg (NL)",
            "Kekerdom (NL)",
            "Keldonk (NL)",
            "Kerk-Avezaath (NL)",
            "Kerkdriel (NL)",
            "Kerkenveld (NL)",
            "Kerkrade (NL)",
            "Kessel (NL)",
            "Kesteren (NL)",
            "Kimswerd (NL)",
            "Kinderdijk (NL)",
            "Klaaswaal (NL)",
            "Klazienaveen (NL)",
            "Klimmen (NL)",
            "Kloetinge (NL)",
            "Kloosterhaar (NL)",
            "Klundert (NL)",
            "Kockengen (NL)",
            "Koedijk (NL)",
            "Koekange (NL)",
            "Koewacht (NL)",
            "Kolham (NL)",
            "Kolhorn (NL)",
            "Kollum (NL)",
            "Kommerzijl (NL)",
            "Koog aan de Zaan (NL)",
            "Kootstertille (NL)",
            "Kootwijkerbroek (NL)",
            "Kortenhoef (NL)",
            "Kortgene (NL)",
            "Koudekerk aan den Rijn (NL)",
            "Koudekerke (NL)",
            "Koudum (NL)",
            "Kraggenburg (NL)",
            "Krimpen aan de Lek (NL)",
            "Krimpen aan den IJssel (NL)",
            "Krommenie (NL)",
            "Kropswolde (NL)",
            "Kruiningen (NL)",
            "Kruisland (NL)",
            "Kudelstaart (NL)",
            "Kuitaart (NL)",
            "Kwintsheul (NL)",
            "Laag-Soeren (NL)",
            "Lage Mierde (NL)",
            "Lage Zwaluwe (NL)",
            "Landsmeer (NL)",
            "Langedijk (NL)",
            "Langezwaag (NL)",
            "Laren (NL)",
            "Lathum (NL)",
            "Leek (NL)",
            "Leerdam (NL)",
            "Leersum (NL)",
            "Leeuwarden (NL)",
            "Legemeer (NL)",
            "Leiden (NL)",
            "Leiderdorp (NL)",
            "Leidschendam (NL)",
            "Leimuiden (NL)",
            "Lekkerkerk (NL)",
            "Lelystad (NL)",
            "Lemele (NL)",
            "Lemelerveld (NL)",
            "Lemiers (NL)",
            "Lemmer (NL)",
            "Lent (NL)",
            "Lettele (NL)",
            "Leusden (NL)",
            "Leuth (NL)",
            "Lewenborg (NL)",
            "Lexmond (NL)",
            "Lichtenvoorde (NL)",
            "Liempde (NL)",
            "Lienden (NL)",
            "Lienden (NL)",
            "Lies (NL)",
            "Lieshout (NL)",
            "Liessel (NL)",
            "Lievelde (NL)",
            "Lijnden (NL)",
            "Limbricht (NL)",
            "Limmel (NL)",
            "Limmen (NL)",
            "Linne (NL)",
            "Linschoten (NL)",
            "Lippenhuizen (NL)",
            "Lisse (NL)",
            "Lithoijen (NL)",
            "Lobith (NL)",
            "Lochem (NL)",
            "Loenen (NL)",
            "Loon op Zand (NL)",
            "Loosdrecht (NL)",
            "Loozen (NL)",
            "Lopik (NL)",
            "Loppersum (NL)",
            "Losser (NL)",
            "Lottum (NL)",
            "Lunteren (NL)",
            "Lutjebroek (NL)",
            "Lutjewinkel (NL)",
            "Lutten (NL)",
            "Luyksgestel (NL)",
            "Maarheeze (NL)",
            "Maarn (NL)",
            "Maarssen (NL)",
            "Maarssenbroek (NL)",
            "Maartensdijk (NL)",
            "Maasbommel (NL)",
            "Maasbracht (NL)",
            "Maasbree (NL)",
            "Maasdam (NL)",
            "Maasdijk (NL)",
            "Maashees (NL)",
            "Maaskantje (NL)",
            "Maasland (NL)",
            "Maassluis (NL)",
            "Maastricht (NL)",
            "Made (NL)",
            "Makkum (NL)",
            "Malden (NL)",
            "Manderveen (NL)",
            "Margraten (NL)",
            "Marienberg (NL)",
            "Markelo (NL)",
            "Marknesse (NL)",
            "Marrum (NL)",
            "Marum (NL)",
            "Mastenbroek (NL)",
            "Maurik (NL)",
            "Mechelen (NL)",
            "Medemblik (NL)",
            "Meeden (NL)",
            "Meer (NL)",
            "Meerkerk (NL)",
            "Meerlo (NL)",
            "Meerssen (NL)",
            "Meeuwen (NL)",
            "Megchelen (NL)",
            "Meijel (NL)",
            "Melick (NL)",
            "Meppel (NL)",
            "Merkelbeek (NL)",
            "Merselo (NL)",
            "Middelbeers (NL)",
            "Middelburg (NL)",
            "Middelharnis (NL)",
            "Middenbeemster (NL)",
            "Middenmeer (NL)",
            "Midlum (NL)",
            "Mierlo (NL)",
            "Mijdrecht (NL)",
            "Mijnsheerenland (NL)",
            "Mildam (NL)",
            "Milheeze (NL)",
            "Mill (NL)",
            "Millingen (NL)",
            "Millingen aan de Rijn (NL)",
            "Milsbeek (NL)",
            "Moerdijk (NL)",
            "Moergestel (NL)",
            "Moerkapelle (NL)",
            "Molenaarsgraaf (NL)",
            "Molenhoek (NL)",
            "Molenhoek (NL)",
            "Molenschot (NL)",
            "Monnickendam (NL)",
            "Monster (NL)",
            "Montfoort (NL)",
            "Montfort (NL)",
            "Mook (NL)",
            "Mookhoek (NL)",
            "Moordrecht (NL)",
            "Mortel (NL)",
            "Muiden (NL)",
            "Muiderberg (NL)",
            "Munstergeleen (NL)",
            "Muntendam (NL)",
            "Mussel (NL)",
            "Naaldwijk (NL)",
            "Naarden (NL)",
            "Nederasselt (NL)",
            "Nederhemert (NL)",
            "Nederhorst den Berg (NL)",
            "Nederweert (NL)",
            "Neede (NL)",
            "Neer (NL)",
            "Neer-Andel (NL)",
            "Nes (NL)",
            "Netterden (NL)",
            "Nibbixwoud (NL)",
            "Nieuw-Amsterdam (NL)",
            "Nieuw-Balinge (NL)",
            "Nieuw-Beijerland (NL)",
            "Nieuw-Bergen (NL)",
            "Nieuw-Buinen (NL)",
            "Nieuw-Dordrecht (NL)",
            "Nieuw-Lekkerland (NL)",
            "Nieuw-Namen (NL)",
            "Nieuw-Schoonebeek (NL)",
            "Nieuw-Vennep (NL)",
            "Nieuw-Vossemeer (NL)",
            "Nieuwdorp (NL)",
            "Nieuwe-Niedorp (NL)",
            "Nieuwe-Tonge (NL)",
            "Nieuwegein (NL)",
            "Nieuwehorne (NL)",
            "Nieuwendijk (NL)",
            "Nieuwe Pekela (NL)",
            "Nieuwer-Ter-Aa (NL)",
            "Nieuwerbrug (NL)",
            "Nieuwerkerk aan den IJssel (NL)",
            "Nieuweschoot (NL)",
            "Nieuwe Wetering (NL)",
            "Nieuwkoop (NL)",
            "Nieuwkuijk (NL)",
            "Nieuwlande (NL)",
            "Nieuwleusen (NL)",
            "Nieuwolda (NL)",
            "Nieuwpoort (NL)",
            "Nieuwstadt (NL)",
            "Nieuwveen (NL)",
            "Nigtevecht (NL)",
            "Nijbroek (NL)",
            "Nijhuizum (NL)",
            "Nijkerk (NL)",
            "Nijkerkerveen (NL)",
            "Nijland (NL)",
            "Nijmegen (NL)",
            "Nijnsel (NL)",
            "Nijverdal (NL)",
            "Nistelrode (NL)",
            "Noardburgum (NL)",
            "Noorbeek (NL)",
            "Noord-Scharwoude (NL)",
            "Noord-Sleen (NL)",
            "Noordbroek (NL)",
            "Noordeloos (NL)",
            "Noorden (NL)",
            "Noordgouwe (NL)",
            "Noordhorn (NL)",
            "Noordlaren (NL)",
            "Noordscheschut (NL)",
            "Noordwelle (NL)",
            "Noordwijk-Binnen (NL)",
            "Noordwijk aan Zee (NL)",
            "Noordwijkerhout (NL)",
            "Noordwolde (NL)",
            "Nootdorp (NL)",
            "Norg (NL)",
            "Nuenen (NL)",
            "Nuis (NL)",
            "Nuland (NL)",
            "Numansdorp (NL)",
            "Nunhem (NL)",
            "Nunspeet (NL)",
            "Nuth (NL)",
            "Obbicht (NL)",
            "Obdam (NL)",
            "Ochten (NL)",
            "Odijk (NL)",
            "Oeffelt (NL)",
            "Oegstgeest (NL)",
            "Oene (NL)",
            "Oijen (NL)",
            "Oirsbeek (NL)",
            "Oirschot (NL)",
            "Oisterwijk (NL)",
            "Oldeberkoop (NL)",
            "Oldebroek (NL)",
            "Oldeholtpade (NL)",
            "Oldehove (NL)",
            "Oldekerk (NL)",
            "Oldemarkt (NL)",
            "Oldenzaal (NL)",
            "Olst (NL)",
            "Ommen (NL)",
            "Onnen (NL)",
            "Ooij (NL)",
            "Ooltgensplaat (NL)",
            "Oost-Souburg (NL)",
            "Oostburg (NL)",
            "Oostendam (NL)",
            "Oosterbeek (NL)",
            "Oosterbierum (NL)",
            "Oosterend (NL)",
            "Oosterhesselen (NL)",
            "Oosterhout (NL)",
            "Oosterland (NL)",
            "Oosternijkerk (NL)",
            "Oosterwolde (NL)",
            "Oosterwolde (NL)",
            "Oosterzee (NL)",
            "Oosthuizen (NL)",
            "Oostkapelle (NL)",
            "Oostvoorne (NL)",
            "Oostwold (NL)",
            "Oostwoud (NL)",
            "Oostzaan (NL)",
            "Ootmarsum (NL)",
            "Op den Bosch (NL)",
            "Opeinde (NL)",
            "Ophemert (NL)",
            "Opheusden (NL)",
            "Opmeer (NL)",
            "Oranje (NL)",
            "Oranjewoud (NL)",
            "Ospel (NL)",
            "Oss (NL)",
            "Ossendrecht (NL)",
            "Oterleek (NL)",
            "Otterlo (NL)",
            "Ottersum (NL)",
            "Oud-Ade (NL)",
            "Oud-Alblas (NL)",
            "Oud-Beijerland (NL)",
            "Oud-Gastel (NL)",
            "Oud-Zuilen (NL)",
            "Ouddorp (NL)",
            "Oude-Tonge (NL)",
            "Oudega (NL)",
            "Oudehaske (NL)",
            "Oudehorne (NL)",
            "Oudelande (NL)",
            "Oudemirdum (NL)",
            "Oudemolen (NL)",
            "Oudenbosch (NL)",
            "Oudendijk (NL)",
            "Oude Pekela (NL)",
            "Ouderkerk aan de Amstel (NL)",
            "Oudeschild (NL)",
            "Oudesluis (NL)",
            "Oudewater (NL)",
            "Oude Wetering (NL)",
            "Oudkarspel (NL)",
            "Oudorp (NL)",
            "Oudwoude (NL)",
            "Overasselt (NL)",
            "Overberg (NL)",
            "Overdinkel (NL)",
            "Overloon (NL)",
            "Overveen (NL)",
            "Ovezande (NL)",
            "Palemig (NL)",
            "Pannerden (NL)",
            "Panningen (NL)",
            "Papekop (NL)",
            "Papendrecht (NL)",
            "Partij (NL)",
            "Paterswolde (NL)",
            "Peize (NL)",
            "Pernis (NL)",
            "Petten (NL)",
            "Philippine (NL)",
            "Piershil (NL)",
            "Pieterburen (NL)",
            "Pieterzijl (NL)",
            "Pijnacker (NL)",
            "Pingjum (NL)",
            "Plasmolen (NL)",
            "Poeldijk (NL)",
            "Poortugaal (NL)",
            "Poortvliet (NL)",
            "Posterholt (NL)",
            "Princenhof (NL)",
            "Prinsenbeek (NL)",
            "Puiflijk (NL)",
            "Purmerend (NL)",
            "Purmerland (NL)",
            "Puth (NL)",
            "Putte (NL)",
            "Putten (NL)",
            "Puttershoek (NL)",
            "Raalte (NL)",
            "Raamsdonksveer (NL)",
            "Randwijk (NL)",
            "Ravenstein (NL)",
            "Ravenswoud (NL)",
            "Reeuwijk (NL)",
            "Rekken (NL)",
            "Renesse (NL)",
            "Renkum (NL)",
            "Renswoude (NL)",
            "Ressen (NL)",
            "Retranchement (NL)",
            "Reusel (NL)",
            "Reuver (NL)",
            "Rheden (NL)",
            "Rhenen (NL)",
            "Rhenoy (NL)",
            "Rhoon (NL)",
            "Ridderkerk (NL)",
            "Riethoven (NL)",
            "Rietveld (NL)",
            "Rijckholt (NL)",
            "Rijen (NL)",
            "Rijkevoort (NL)",
            "Rijnsburg (NL)",
            "Rijpwetering (NL)",
            "Rijsbergen (NL)",
            "Rijsenhout (NL)",
            "Rijssen (NL)",
            "Rijswijk (NL)",
            "Rijswijk (NL)",
            "Rilland (NL)",
            "Rinsumageast (NL)",
            "Rips (NL)",
            "Rivierenwijk (NL)",
            "Rixtel (NL)",
            "Rockanje (NL)",
            "Roden (NL)",
            "Rodenrijs (NL)",
            "Roelofarendsveen (NL)",
            "Roermond (NL)",
            "Roggel (NL)",
            "Rolde (NL)",
            "Roodeschool (NL)",
            "Roosendaal (NL)",
            "Roosteren (NL)",
            "Rooth (NL)",
            "Rosmalen (NL)",
            "Rossum (NL)",
            "Rossum (NL)",
            "Rotterdam (NL)",
            "Rottum (NL)",
            "Rottum (NL)",
            "Rozenburg (NL)",
            "Rozenburg (NL)",
            "Rozendaal (NL)",
            "Rucphen (NL)",
            "Ruinen (NL)",
            "Ruinerwold (NL)",
            "Rutten (NL)",
            "Ruurlo (NL)",
            "s-Heerenberg (NL)",
            "Saasveld (NL)",
            "Sambeek (NL)",
            "Santpoort-Noord (NL)",
            "Sappemeer (NL)",
            "Sassenheim (NL)",
            "Sas van Gent (NL)",
            "Schagen (NL)",
            "Schagerbrug (NL)",
            "Schaijk (NL)",
            "Schalkhaar (NL)",
            "Scharmer (NL)",
            "Scheemda (NL)",
            "Schellinkhout (NL)",
            "Schermerhorn (NL)",
            "Scherpenisse (NL)",
            "Scherpenzeel (NL)",
            "Schiedam (NL)",
            "Schiermonnikoog (NL)",
            "Schijndel (NL)",
            "Schildwolde (NL)",
            "Schimmert (NL)",
            "Schinnen (NL)",
            "Schin op Geul (NL)",
            "Schinveld (NL)",
            "Schipborg (NL)",
            "Schipluiden (NL)",
            "Schoondijke (NL)",
            "Schoonebeek (NL)",
            "Schoonhoven (NL)",
            "Schoorl (NL)",
            "Schore (NL)",
            "Sellingen (NL)",
            "Serooskerke (NL)",
            "Sevenum (NL)",
            "Sibculo (NL)",
            "Siddeburen (NL)",
            "Siebengewald (NL)",
            "Silvolde (NL)",
            "Simpelveld (NL)",
            "Sint-Michielsgestel (NL)",
            "Sint-Oedenrode (NL)",
            "Sint Agatha (NL)",
            "Sint Annaland (NL)",
            "Sint Annaparochie (NL)",
            "Sint Anthonis (NL)",
            "Sint Hubert (NL)",
            "Sint Jansteen (NL)",
            "Sintjohannesga (NL)",
            "Sint Joost (NL)",
            "Sint Maarten (NL)",
            "Sint Maartensdijk (NL)",
            "Sint Nicolaasga (NL)",
            "Sint Odilienberg (NL)",
            "Sint Pancras (NL)",
            "Sint Philipsland (NL)",
            "Sint Willebrord (NL)",
            "Sittard (NL)",
            "Slagharen (NL)",
            "Sleen (NL)",
            "Sleeuwijk (NL)",
            "Slenaken (NL)",
            "Sliedrecht (NL)",
            "Slijk-Ewijk (NL)",
            "Slochteren (NL)",
            "Slootdorp (NL)",
            "Sloterdijk (NL)",
            "Sluis (NL)",
            "Sluiskil (NL)",
            "Smilde (NL)",
            "Sneek (NL)",
            "Soerendonk (NL)",
            "Soest (NL)",
            "Soesterberg (NL)",
            "Someren (NL)",
            "Sommelsdijk (NL)",
            "Son en Breugel (NL)",
            "Spaarndam (NL)",
            "Spakenburg (NL)",
            "Spanbroek (NL)",
            "Spaubeek (NL)",
            "Spierdijk (NL)",
            "Spijk (NL)",
            "Spijkenisse (NL)",
            "Sprang (NL)",
            "Sprundel (NL)",
            "Stad aan 't Haringvliet (NL)",
            "Stadskanaal (NL)",
            "Stampersgat (NL)",
            "Staphorst (NL)",
            "Stationsbuurt (NL)",
            "Stedum (NL)",
            "Steenbergen (NL)",
            "Steensel (NL)",
            "Steenwijk (NL)",
            "Steggerda (NL)",
            "Steijl (NL)",
            "Stein (NL)",
            "Stellendam (NL)",
            "Sterksel (NL)",
            "Stevensbeek (NL)",
            "Stevensweert (NL)",
            "Stiens (NL)",
            "Stolwijk (NL)",
            "Stompetoren (NL)",
            "Stompwijk (NL)",
            "Stoutenburg (NL)",
            "Strijen (NL)",
            "Strijensas (NL)",
            "Stroe (NL)",
            "Stuifzand (NL)",
            "Sumar (NL)",
            "Surhuisterveen (NL)",
            "Surhuizum (NL)",
            "Susteren (NL)",
            "Suwald (NL)",
            "Swalmen (NL)",
            "Sweikhuizen (NL)",
            "Swifterbant (NL)",
            "Taarlo (NL)",
            "Tegelen (NL)",
            "Ten Boer (NL)",
            "Ten Post (NL)",
            "Ter Aar (NL)",
            "Ter Apel (NL)",
            "Ter Apelkanaal (NL)",
            "Terblijt (NL)",
            "Terborg (NL)",
            "Terheijden (NL)",
            "Terneuzen (NL)",
            "Terschuur (NL)",
            "Teteringen (NL)",
            "The Hague (NL)",
            "Tholen (NL)",
            "Tiel (NL)",
            "Tienhoven (NL)",
            "Tienraij (NL)",
            "Tijnje (NL)",
            "Tilburg (NL)",
            "Tilligte (NL)",
            "Tinte (NL)",
            "Tjerkwerd (NL)",
            "Tolbert (NL)",
            "Toldijk (NL)",
            "Tolkamer (NL)",
            "Tricht (NL)",
            "Tubbergen (NL)",
            "Tuitjenhorn (NL)",
            "Tull (NL)",
            "Tweede Exloermond (NL)",
            "Tweede Valthermond (NL)",
            "Twello (NL)",
            "Twijzelerheide (NL)",
            "Twisk (NL)",
            "Tynaarlo (NL)",
            "Tytsjerk (NL)",
            "Tzummarum (NL)",
            "Uddel (NL)",
            "Uden (NL)",
            "Udenhout (NL)",
            "Ugchelen (NL)",
            "Uitdam (NL)",
            "Uitgeest (NL)",
            "Uithoorn (NL)",
            "Uithuizen (NL)",
            "Uithuizermeeden (NL)",
            "Uitwellingerga (NL)",
            "Ulestraten (NL)",
            "Ulft (NL)",
            "Ulicoten (NL)",
            "Ulrum (NL)",
            "Ulvenhout (NL)",
            "Ureterp (NL)",
            "Urk (NL)",
            "Urmond (NL)",
            "Ursem (NL)",
            "Utrecht (NL)",
            "Vaals (NL)",
            "Vaassen (NL)",
            "Valburg (NL)",
            "Valkenburg (NL)",
            "Valkenburg (NL)",
            "Valkenswaard (NL)",
            "Valthe (NL)",
            "Valthermond (NL)",
            "Varik (NL)",
            "Varsseveld (NL)",
            "Vasse (NL)",
            "Veen (NL)",
            "Veendam (NL)",
            "Veenendaal (NL)",
            "Veenhuizen (NL)",
            "Veenoord (NL)",
            "Veghel (NL)",
            "Velddriel (NL)",
            "Velden (NL)",
            "Veldhoven (NL)",
            "Velp (NL)",
            "Velsen (NL)",
            "Velsen-Noord (NL)",
            "Ven-Zelderheide (NL)",
            "Venhorst (NL)",
            "Venhuizen (NL)",
            "Venlo (NL)",
            "Venray (NL)",
            "Vianen (NL)",
            "Vierhouten (NL)",
            "Vierlingsbeek (NL)",
            "Vierpolders (NL)",
            "Vijfhuizen (NL)",
            "Vilt (NL)",
            "Vinkeveen (NL)",
            "Vlaardingen (NL)",
            "Vlagtwedde (NL)",
            "Vledder (NL)",
            "Vleuten (NL)",
            "Vlieland (NL)",
            "Vlijmen (NL)",
            "Vlodrop (NL)",
            "Voerendaal (NL)",
            "Vogelenzang (NL)",
            "Vogelwaarde (NL)",
            "Volendam (NL)",
            "Volkel (NL)",
            "Voorburg (NL)",
            "Voorhout (NL)",
            "Voorschoten (NL)",
            "Voorst (NL)",
            "Voorthuizen (NL)",
            "Vorden (NL)",
            "Vorstenbosch (NL)",
            "Vortum-Mullem (NL)",
            "Vragender (NL)",
            "Vreeland (NL)",
            "Vries (NL)",
            "Vriezenveen (NL)",
            "Vroomshoop (NL)",
            "Vrouwenpolder (NL)",
            "Vught (NL)",
            "Vuren (NL)",
            "Waalre (NL)",
            "Waalwijk (NL)",
            "Waardenburg (NL)",
            "Waarder (NL)",
            "Waarland (NL)",
            "Waddinxveen (NL)",
            "Wagenberg (NL)",
            "Wagenborgen (NL)",
            "Wageningen (NL)",
            "Walterswald (NL)",
            "Wamel (NL)",
            "Wanroij (NL)",
            "Wanssum (NL)",
            "Wapenveld (NL)",
            "Warder (NL)",
            "Warffum (NL)",
            "Warmenhuizen (NL)",
            "Warmond (NL)",
            "Warnsveld (NL)",
            "Waspik (NL)",
            "Wassenaar (NL)",
            "Wateringen (NL)",
            "Waterland (NL)",
            "Weerselo (NL)",
            "Weert (NL)",
            "Weesp (NL)",
            "Wehl (NL)",
            "Weidum (NL)",
            "Well (NL)",
            "Wellerlooi (NL)",
            "Wemeldinge (NL)",
            "Werkendam (NL)",
            "Werkhoven (NL)",
            "Wervershoof (NL)",
            "Wessem (NL)",
            "West-Knollendam (NL)",
            "West-Terschelling (NL)",
            "Westbeemster (NL)",
            "Westbroek (NL)",
            "Westdorpe (NL)",
            "Westerbork (NL)",
            "Westerhaar-Vriezenveensewijk (NL)",
            "Westerhoven (NL)",
            "Westervoort (NL)",
            "Westerwijtwerd (NL)",
            "Westkapelle (NL)",
            "Westmaas (NL)",
            "Westzaan (NL)",
            "Weurt (NL)",
            "Wezep (NL)",
            "Wierden (NL)",
            "Wieringerwaard (NL)",
            "Wieringerwerf (NL)",
            "Wierum (NL)",
            "Wijchen (NL)",
            "Wijckel (NL)",
            "Wijdenes (NL)",
            "Wijdewormer (NL)",
            "Wijhe (NL)",
            "Wijk aan Zee (NL)",
            "Wijk bij Duurstede (NL)",
            "Wijlre (NL)",
            "Wijnaldum (NL)",
            "Wijnandsrade (NL)",
            "Wijngaarden (NL)",
            "Wijster (NL)",
            "Wildervank (NL)",
            "Willemstad (NL)",
            "Wilnis (NL)",
            "Wilp (NL)",
            "Winkel (NL)",
            "Winschoten (NL)",
            "Winssen (NL)",
            "Winsum (NL)",
            "Wintelre (NL)",
            "Winterswijk (NL)",
            "Wissenkerke (NL)",
            "Witharen (NL)",
            "Wittem (NL)",
            "Witteveen (NL)",
            "Woensdrecht (NL)",
            "Woerden (NL)",
            "Woerdense Verlaat (NL)",
            "Wognum (NL)",
            "Wolfheze (NL)",
            "Wolphaartsdijk (NL)",
            "Woltersum (NL)",
            "Wolvega (NL)",
            "Wommels (NL)",
            "Wons (NL)",
            "Workum (NL)",
            "Wormer (NL)",
            "Wormerveer (NL)",
            "Woubrugge (NL)",
            "Woudenberg (NL)",
            "Woudrichem (NL)",
            "Woudsend (NL)",
            "Wouwsche Plantage (NL)",
            "Yde (NL)",
            "Yerseke (NL)",
            "Ysbrechtum (NL)",
            "Zaamslag (NL)",
            "Zaandam (NL)",
            "Zaandijk (NL)",
            "Zaanstad (NL)",
            "Zalk (NL)",
            "Zaltbommel (NL)",
            "Zandeweer (NL)",
            "Zandvoort (NL)",
            "Zeddam (NL)",
            "Zeeland (NL)",
            "Zeerijp (NL)",
            "Zeewolde (NL)",
            "Zeist (NL)",
            "Zelhem (NL)",
            "Zetten (NL)",
            "Zevenaar (NL)",
            "Zevenbergen (NL)",
            "Zevenbergschen Hoek (NL)",
            "Zevenhoven (NL)",
            "Zevenhuizen (NL)",
            "Zierikzee (NL)",
            "Zieuwent (NL)",
            "Zijderveld (NL)",
            "Zoetermeer (NL)",
            "Zoeterwoude (NL)",
            "Zonnemaire (NL)",
            "Zorgvlied (NL)",
            "Zoutelande (NL)",
            "Zoutkamp (NL)",
            "Zuid-Beijerland (NL)",
            "Zuid-Scharwoude (NL)",
            "Zuidbroek (NL)",
            "Zuidermeer (NL)",
            "Zuiderpark (NL)",
            "Zuidhorn (NL)",
            "Zuidland (NL)",
            "Zuidlaren (NL)",
            "Zuidoostbeemster (NL)",
            "Zuidwolde (NL)",
            "Zuidzande (NL)",
            "Zuilichem (NL)",
            "Zundert (NL)",
            "Zutphen (NL)",
            "Zwaag (NL)",
            "Zwaagdijk-Oost (NL)",
            "Zwaanshoek (NL)",
            "Zwanenburg (NL)",
            "Zwartebroek (NL)",
            "Zwartemeer (NL)",
            "Zwartewaal (NL)",
            "Zwartsluis (NL)",
            "Zwijndrecht (NL)",
            "Zwinderen (NL)",
            "Zwolle (NL)"
        ],
        'be' => [
            "Aalst (BE)",
            "Aalter (BE)",
            "Aarschot (BE)",
            "Aartselaar (BE)",
            "Affligem (BE)",
            "Alken (BE)",
            "Alveringem (BE)",
            "Antwerpen (BE)",
            "Anzegem (BE)",
            "Ardooie (BE)",
            "Arendonk (BE)",
            "As (BE)",
            "Asse (BE)",
            "Assenede (BE)",
            "Avelgem (BE)",
            "Baarle-Hertog (BE)",
            "Balen (BE)",
            "Beernem (BE)",
            "Beerse (BE)",
            "Beersel (BE)",
            "Begijnendijk (BE)",
            "Bekkevoort (BE)",
            "Beringen (BE)",
            "Berlaar (BE)",
            "Berlare (BE)",
            "Bertem (BE)",
            "Bever (BE)",
            "Beveren (BE)",
            "Bierbeek (BE)",
            "Bilzen (BE)",
            "Blankenberge (BE)",
            "Bocholt (BE)",
            "Boechout (BE)",
            "Bonheiden (BE)",
            "Boom (BE)",
            "Boortmeerbeek (BE)",
            "Borgloon (BE)",
            "Bornem (BE)",
            "Borsbeek (BE)",
            "Boutersem (BE)",
            "Brakel (BE)",
            "Brasschaat (BE)",
            "Brecht (BE)",
            "Bredene (BE)",
            "Bree (BE)",
            "Brugge (BE)",
            "Brussel (BE)",
            "Buggenhout (BE)",
            "Damme (BE)",
            "De Haan (BE)",
            "De Panne (BE)",
            "De Pinte (BE)",
            "Deerlijk (BE)",
            "Deinze (BE)",
            "Denderleeuw (BE)",
            "Dendermonde (BE)",
            "Dentergem (BE)",
            "Dessel (BE)",
            "Destelbergen (BE)",
            "Diepenbeek (BE)",
            "Diest (BE)",
            "Diksmuide (BE)",
            "Dilbeek (BE)",
            "Dilsen-Stokkem (BE)",
            "Drogenbos (BE)",
            "Duffel (BE)",
            "Edegem (BE)",
            "Eeklo (BE)",
            "Erpe-Mere (BE)",
            "Essen (BE)",
            "Evergem (BE)",
            "Galmaarden (BE)",
            "Gavere (BE)",
            "Geel (BE)",
            "Geetbets (BE)",
            "Genk (BE)",
            "Gent (BE)",
            "Geraardsbergen (BE)",
            "Gingelom (BE)",
            "Gistel (BE)",
            "Glabbeek (BE)",
            "Gooik (BE)",
            "Grimbergen (BE)",
            "Grobbendonk (BE)",
            "Haacht (BE)",
            "Haaltert (BE)",
            "Halen (BE)",
            "Halle (BE)",
            "Ham (BE)",
            "Hamme (BE)",
            "Hamont-Achel (BE)",
            "Harelbeke (BE)",
            "Hasselt (BE)",
            "Hechtel-Eksel (BE)",
            "Heers (BE)",
            "Heist-op-den-Berg (BE)",
            "Hemiksem (BE)",
            "Herent (BE)",
            "Herentals (BE)",
            "Herenthout (BE)",
            "Herk-de-Stad (BE)",
            "Herne (BE)",
            "Herselt (BE)",
            "Herstappe (BE)",
            "Herzele (BE)",
            "Heusden-Zolder (BE)",
            "Heuvelland (BE)",
            "Hoegaarden (BE)",
            "Hoeilaart (BE)",
            "Hoeselt (BE)",
            "Holsbeek (BE)",
            "Hooglede (BE)",
            "Hoogstraten (BE)",
            "Horebeke (BE)",
            "Houthalen-Helchteren (BE)",
            "Houthulst (BE)",
            "Hove (BE)",
            "Huldenberg (BE)",
            "Hulshout (BE)",
            "Ichtegem (BE)",
            "Ieper (BE)",
            "Ingelmunster (BE)",
            "Izegem (BE)",
            "Jabbeke (BE)",
            "Kalmthout (BE)",
            "Kampenhout (BE)",
            "Kapelle-op-den-Bos (BE)",
            "Kapellen (BE)",
            "Kaprijke (BE)",
            "Kasterlee (BE)",
            "Keerbergen (BE)",
            "Kinrooi (BE)",
            "Kluisbergen (BE)",
            "Knokke-Heist (BE)",
            "Koekelare (BE)",
            "Koksijde (BE)",
            "Kontich (BE)",
            "Kortemark (BE)",
            "Kortenaken (BE)",
            "Kortenberg (BE)",
            "Kortessem (BE)",
            "Kortrijk (BE)",
            "Kraainem (BE)",
            "Kruibeke (BE)",
            "Kruisem (BE)",
            "Kuurne (BE)",
            "Laakdal (BE)",
            "Laarne (BE)",
            "Lanaken (BE)",
            "Landen (BE)",
            "Langemark-Poelkapelle (BE)",
            "Lebbeke (BE)",
            "Lede (BE)",
            "Ledegem (BE)",
            "Lendelede (BE)",
            "Lennik (BE)",
            "Leopoldsburg (BE)",
            "Leuven (BE)",
            "Lichtervelde (BE)",
            "Liedekerke (BE)",
            "Lier (BE)",
            "Lierde (BE)",
            "Lievegem (BE)",
            "Lille (BE)",
            "Linkebeek (BE)",
            "Lint (BE)",
            "Linter (BE)",
            "Lo-Reninge (BE)",
            "Lochristi (BE)",
            "Lokeren (BE)",
            "Lommel (BE)",
            "Londerzeel (BE)",
            "Lubbeek (BE)",
            "Lummen (BE)",
            "Maarkedal (BE)",
            "Maaseik (BE)",
            "Maasmechelen (BE)",
            "Machelen (BE)",
            "Maldegem (BE)",
            "Malle (BE)",
            "Mechelen (BE)",
            "Meerhout (BE)",
            "Meise (BE)",
            "Melle (BE)",
            "Menen (BE)",
            "Merchtem (BE)",
            "Merelbeke (BE)",
            "Merksplas (BE)",
            "Mesen (BE)",
            "Meulebeke (BE)",
            "Middelkerke (BE)",
            "Moerbeke (BE)",
            "Mol (BE)",
            "Moorslede (BE)",
            "Mortsel (BE)",
            "Nazareth (BE)",
            "Niel (BE)",
            "Nieuwerkerken (BE)",
            "Nieuwpoort (BE)",
            "Nijlen (BE)",
            "Ninove (BE)",
            "Olen (BE)",
            "Oostende (BE)",
            "Oosterzele (BE)",
            "Oostkamp (BE)",
            "Oostrozebeke (BE)",
            "Opwijk (BE)",
            "Oud-Heverlee (BE)",
            "Oud-Turnhout (BE)",
            "Oudenaarde (BE)",
            "Oudenburg (BE)",
            "Oudsbergen (BE)",
            "Overijse (BE)",
            "Peer (BE)",
            "Pelt (BE)",
            "Pepingen (BE)",
            "Pittem (BE)",
            "Poperinge (BE)",
            "Putte (BE)",
            "Puurs-Sint-Amands (BE)",
            "Ranst (BE)",
            "Ravels (BE)",
            "Retie (BE)",
            "Riemst (BE)",
            "Rijkevorsel (BE)",
            "Roeselare (BE)",
            "Ronse (BE)",
            "Roosdaal (BE)",
            "Rotselaar (BE)",
            "Ruiselede (BE)",
            "Rumst (BE)",
            "Schelle (BE)",
            "Scherpenheuvel-Zichem (BE)",
            "Schilde (BE)",
            "Schoten (BE)",
            "Sint-Genesius-Rode (BE)",
            "Sint-Gillis-Waas (BE)",
            "Sint-Katelijne-Waver (BE)",
            "Sint-Laureins (BE)",
            "Sint-Lievens-Houtem (BE)",
            "Sint-Martens-Latem (BE)",
            "Sint-Niklaas (BE)",
            "Sint-Pieters-Leeuw (BE)",
            "Sint-Truiden (BE)",
            "Spiere-Helkijn (BE)",
            "Stabroek (BE)",
            "Staden (BE)",
            "Steenokkerzeel (BE)",
            "Stekene (BE)",
            "Temse (BE)",
            "Ternat (BE)",
            "Tervuren (BE)",
            "Tessenderlo (BE)",
            "Tielt (BE)",
            "Tielt-Winge (BE)",
            "Tienen (BE)",
            "Tongeren (BE)",
            "Torhout (BE)",
            "Tremelo (BE)",
            "Turnhout (BE)",
            "Veurne (BE)",
            "Vilvoorde (BE)",
            "Vleteren (BE)",
            "Voeren (BE)",
            "Vorselaar (BE)",
            "Vosselaar (BE)",
            "Waasmunster (BE)",
            "Wachtebeke (BE)",
            "Waregem (BE)",
            "Wellen (BE)",
            "Wemmel (BE)",
            "Wervik (BE)",
            "Westerlo (BE)",
            "Wetteren (BE)",
            "Wevelgem (BE)",
            "Wezembeek-Oppem (BE)",
            "Wichelen (BE)",
            "Wielsbeke (BE)",
            "Wijnegem (BE)",
            "Willebroek (BE)",
            "Wingene (BE)",
            "Wommelgem (BE)",
            "Wortegem-Petegem (BE)",
            "Wuustwezel (BE)",
            "Zandhoven (BE)",
            "Zaventem (BE)",
            "Zedelgem (BE)",
            "Zele (BE)",
            "Zelzate (BE)",
            "Zemst (BE)",
            "Zoersel (BE)",
            "Zonhoven (BE)",
            "Zonnebeke (BE)",
            "Zottegem (BE)",
            "Zoutleeuw (BE)",
            "Zuienkerke (BE)",
            "Zulte (BE)",
            "Zutendaal (BE)",
            "Zwalm (BE)",
            "Zwevegem (BE)",
            "Zwijndrecht (BE)"
        ]
    ];

    /**
     * @param string $userRoleName
     * @param string $visibility
     * @return array|null
     */
    public static function selectableFields(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $result = [];

        if (isset(self::$selectableFields['common'][$visibility])) {
            $result = array_merge($result, self::$selectableFields['common'][$visibility]);
        }

        if (isset(self::$selectableFields[$userRoleName][$visibility])) {
            $result = array_merge($result, self::$selectableFields[$userRoleName][$visibility]);
        }

        return (empty($result)) ? null : $result;
    }

    /**
     * @param string $fieldName
     * @param string $userRoleName
     * @param string $arrayManipulationMethodName
     * @return mixed|null
     * @throws \Exception
     */
    public static function selectableField(
        string $fieldName,
        string $userRoleName = 'bot',
        string $arrayManipulationMethodName = ''
    ) {
        $data = self::getSelectableFieldData($fieldName, $userRoleName);

        if ($arrayManipulationMethodName != '') {
            $data = self::applyArrayMethod($arrayManipulationMethodName, $data);
        }

        if (!empty($data)) {
            return $data;
        }

        return null;
    }

    /**
     * @param string $userRoleName
     * @param string $visibility
     * @return array|null
     */
    public static function userTableFields(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $visibilities = ['public', 'private'];

        $result = [];

        if ($visibility == 'all') {
            foreach ($visibilities as $v) {
                if (isset(self::$userTableFields['common'][$v])) {
                    $result = array_merge($result, self::$userTableFields['common'][$v]);
                }

                if (isset(self::$userTableFields[$userRoleName][$v])) {
                    $result = array_merge($result, self::$userTableFields[$userRoleName][$v]);
                }
            }
        } else {
            if (isset(self::$userTableFields['common'][$visibility])) {
                $result = array_merge($result, self::$userTableFields['common'][$visibility]);
            }

            if (isset(self::$userTableFields[$userRoleName][$visibility])) {
                $result = array_merge($result, self::$userTableFields[$userRoleName][$visibility]);
            }
        }

        return (empty($result)) ? null : $result;
    }

    /**
     * @param string $userRoleName
     * @param string $visibility
     * @return array|null
     */
    public static function textFields(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $visibilities = ['public', 'private'];

        $result = [];

        if ($visibility == 'all') {
            foreach ($visibilities as $v) {
                if (isset(self::$textFields['common'][$v])) {
                    $result = array_merge($result, self::$textFields['common'][$v]);
                }

                if (isset(self::$textFields[$userRoleName][$v])) {
                    $result = array_merge($result, self::$textFields[$userRoleName][$v]);
                }

            }
        } else {
            if (isset(self::$textFields['common'][$visibility])) {
                $result = array_merge($result, self::$textFields['common'][$visibility]);
            }

            if (isset(self::$textFields[$userRoleName][$visibility])) {
                $result = array_merge($result, self::$textFields[$userRoleName][$visibility]);
            }
        }

        return (empty($result)) ? null : $result;
    }

    public static function textInputs(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $visibilities = ['public', 'private'];

        $result = [];

        if ($visibility == 'all') {
            foreach ($visibilities as $v) {
                if (isset(self::$textInputs['common'][$v])) {
                    $result = array_merge($result, self::$textInputs['common'][$v]);
                }

                if (isset(self::$textInputs[$userRoleName][$v])) {
                    $result = array_merge($result, self::$textInputs[$userRoleName][$v]);
                }
            }
        } else {
            if (isset(self::$textInputs['common'][$visibility])) {
                $result = array_merge($result, self::$textInputs['common'][$visibility]);
            }

            if (isset(self::$textInputs[$userRoleName][$visibility])) {
                $result = array_merge($result, self::$textInputs[$userRoleName][$visibility]);
            }
        }

        return (empty($result)) ? null : $result;
    }


    /**
     * @param string $userRoleName
     * @return array
     */
    public static function publicFieldNames(string $userRoleName = 'bot')
    {
        return array_merge(
            array_keys(self::selectableFields($userRoleName, 'public')),
            array_keys(self::userTableFields($userRoleName, 'public')),
            self::textFields($userRoleName, 'public'),
            self::textInputs($userRoleName, 'public')
        );
    }

    /**
     * @param string $fieldName
     * @param string $userRoleName
     * @return mixed
     */
    private static function getSelectableFieldData(string $fieldName, string $userRoleName)
    {
        $data = [];

        if (
            isset(self::$selectableFields['common']['public']) &&
            in_array($fieldName, array_keys(self::$selectableFields['common']['public']))
        ) {
            $data = self::$selectableFields['common']['public'][$fieldName];
            return $data;
        } elseif (
            isset(self::$selectableFields[$userRoleName]['public']) &&
            in_array($fieldName, array_keys(self::$selectableFields[$userRoleName]['public']))
        ) {
            $data = self::$selectableFields['common']['public'][$fieldName];
            return $data;
        } elseif (
            isset(self::$selectableFields['common']['private']) &&
            in_array($fieldName, array_keys(self::$selectableFields['common']['private']))
        ) {
            $data = self::$selectableFields['common']['private'][$fieldName];
            return $data;
        } elseif (
            isset(self::$selectableFields[$userRoleName]['private']) &&
            in_array($fieldName, array_keys(self::$selectableFields[$userRoleName]['private']))
        ) {
            $data = self::$selectableFields[$userRoleName]['private'][$fieldName];
            return $data;
        }
        return $data;
    }

    /**
     * @param string $arrayManipulationMethodName
     * @param $data
     * @return mixed
     * @throws \Exception
     */
    private static function applyArrayMethod(string $arrayManipulationMethodName, array $data)
    {
        $allowedArrayManipulations = [
            'array_flip',
            'array_keys',
            'array_values'
        ];

        if (!in_array($arrayManipulationMethodName, $allowedArrayManipulations)) {
            throw new \Exception;
        }

        $data = call_user_func($arrayManipulationMethodName, $data);
        return $data;
    }

    /**
     * @return array
     */
    public static function getCities(string $countryCode = null, string $userCountryCode = null)
    {
        if (null === $countryCode) {
            if ($userCountryCode && $userCountryCode == 'be') {
                $allCities = array_merge(
                    self::$cities['be'],
                    self::$cities['nl']
                );
            } else {
                $allCities = array_merge(
                    self::$cities['nl'],
                    self::$cities['be']
                );

            }

            return $allCities;
        }

        return self::$cities[$countryCode];
    }
}
