<?php namespace App\Helpers\ApplicationConstants;

/**
 * Class UserConstants
 * @package App\Helpers\ApplicationConstants
 */
class UserConstants
{
    public static $maxAmountOnline = 30;

    public static $ageGroups = [
        '18-25' => '18-25',
        '25-30' => '26-35',
        '30-35' => '36-45',
        '46+' => '46+'
    ];

    public static $radiuses = [
        '20',
        '40',
        '60',
    ];

    public static function getAgeGroups() {
        return self::$ageGroups;
    }

    public static function getRadiuses() {
        return self::$radiuses;
    }


    /**
     * @return int
     */
    public static function getMaxAmountOnline()
    {
        return self::$maxAmountOnline;
    }


    public static $userTableFields = [
        'common' => [
            'public' => [
                'username'
            ],
            'private' => [
                'password',
                'account_type',
                'active'
            ],
        ],
        'peasant' => [
            'public' => [
                'email'
            ]
        ]
    ];

    public static $selectableFields = [
        'common' => [
            'public' => [
                'gender' => [
                    1 => 'male',
                    2 => 'female'
                ],
                'looking_for_gender' => [
                    1 => 'male',
                    2 => 'female'
                ],
                'relationship_status' => [
                    1 => 'single',
                    2 => 'in_a_relationship',
                    3 => 'complicated'
                ],
                'body_type' => [
                    1 => 'slender',
                    2 => 'average',
                    3 => 'athletic',
                    4 => 'curvy',
                    5 => 'big'
                ],
                'height' => [
                    1 => '<140',
                    2 => '140-150',
                    3 => '150-160',
                    4 => '160-170',
                    5 => '170-180',
                    6 => '180-190',
                    7 => '190-200',
                    8 => '>200'
                ],
                'eye_color' => [
                    1 => 'green',
                    2 => 'blue',
                    3 => 'brown',
                    4 => 'hazel',
                    5 => 'black'
                ],
                'hair_color' => [
                    1 => 'black',
                    2 => 'grey',
                    3 => 'white',
                    4 => 'brown',
                    5 => 'blond',
                    6 => 'dark_blond',
                    7 => 'red',
                    8 => 'pink'
                ],
                'smoking_habits' => [
                    1 => 'regular',
                    2 => 'social',
                    3 => 'none'
                ],
                'drinking_habits' => [
                    1 => 'regular',
                    2 => 'social',
                    3 => 'none'
                ]
            ],
            'private' => [
                'role' => [
                    1 => 'admin',
                    2 => 'peasant',
                    3 => 'bot',
                    4 => 'operator',
                    5 => 'editor'
                ],
                'account_type' => [
                    1 => 'free',
                    2 => 'small',
                    3 => 'medium',
                    4 => 'large',
                ]
            ]
        ],
        'bot' => [
            'private' => [
                'category' => [
                    1 => 'seniors',
                    2 => 'teens',
                    3 => 'naked',
                    4 => 'dressed',
                ]
            ]
        ]
    ];

    public static $textFields = [
        'common' => [
            'public' => [
                'about_me'
            ]
        ]
    ];

    public static $textInputs = [
        'common' => [
            'public' => [
                'dob',
                'city',
                'country'
            ],
            'private' => [
                'lat',
                'lng'
            ]
        ]
    ];

    public static $immutableFields = [
        'gender'
    ];

    public static $cities = [
        'nl' => [
            "'s-Graveland",
            "'s-Gravendeel",
            "'s-Gravenpolder",
            "'s-Gravenzande",
            "'s-Heer-Hendrikskinderen",
            "'s-Heerenhoek",
            "'s-Hertogenbosch",
            "'s Gravenmoer",
            "'t Harde",
            "'t Kabel",
            "'t Zand",
            "Aagtekerke",
            "Aalburg",
            "Aalden",
            "Aalsmeer",
            "Aalsmeerderbrug",
            "Aalst",
            "Aalten",
            "Aardenburg",
            "Abbekerk",
            "Abbenes",
            "Abcoude",
            "Achterberg",
            "Achterveld",
            "Achthuizen",
            "Achtmaal",
            "Aduard",
            "Aerdenhout",
            "Aerdt",
            "Afferden",
            "Akersloot",
            "Akkrum",
            "Albergen",
            "Alblasserdam",
            "Alde Leie",
            "Alem",
            "Alkmaar",
            "Almelo",
            "Almere",
            "Almere Haven",
            "Almkerk",
            "Alphen",
            "Alphen aan den Rijn",
            "Ameide",
            "America",
            "Amerongen",
            "Amersfoort",
            "Ammerstol",
            "Ammerzoden",
            "Amstelhoek",
            "Amstelveen",
            "Amstenrade",
            "Amsterdam",
            "Anderen",
            "Andijk",
            "Ane",
            "Angeren",
            "Anjum",
            "Ankeveen",
            "Anloo",
            "Anna Paulowna",
            "Annen",
            "Apeldoorn",
            "Appelscha",
            "Appeltern",
            "Appingedam",
            "Arcen",
            "Arkel",
            "Arnemuiden",
            "Arnhem",
            "Asperen",
            "Assen",
            "Assendelft",
            "Asten",
            "Augustinusga",
            "Avenhorn",
            "Axel",
            "Baambrugge",
            "Baarland",
            "Baarle-Nassau",
            "Baarlo",
            "Baarn",
            "Baars",
            "Babberich",
            "Badhoevedorp",
            "Baexem",
            "Bakel",
            "Baken",
            "Bakhuizen",
            "Balgoij",
            "Balk",
            "Ballum",
            "Banholt",
            "Barchem",
            "Barendrecht",
            "Barneveld",
            "Batenburg",
            "Bathmen",
            "Bavel",
            "Bedum",
            "Beegden",
            "Beek",
            "Beek",
            "Beek",
            "Beekbergen",
            "Beerta",
            "Beerzerveld",
            "Beesd",
            "Beesel",
            "Beets",
            "Beetsterzwaag",
            "Beilen",
            "Beinsdorp",
            "Belfeld",
            "Bellingwolde",
            "Bemelen",
            "Bemmel",
            "Beneden-Leeuwen",
            "Bennebroek",
            "Bennekom",
            "Benningbroek",
            "Benthuizen",
            "Berg",
            "Bergambacht",
            "Bergeijk",
            "Bergen",
            "Bergen",
            "Berg en Dal",
            "Bergen op Zoom",
            "Bergentheim",
            "Bergharen",
            "Berghem",
            "Bergschenhoek",
            "Beringe",
            "Berkenwoude",
            "Berkhout",
            "Berlicum",
            "Best",
            "Beugen",
            "Beuningen",
            "Beusichem",
            "Beverwijk",
            "Biddinghuizen",
            "Bierum",
            "Biervliet",
            "Biest",
            "Bilthoven",
            "Bitgum",
            "Bladel",
            "Blaricum",
            "Bleiswijk",
            "Blerick",
            "Bleskensgraaf",
            "Blitterswijck",
            "Bloemendaal",
            "Blokker",
            "Blokzijl",
            "Bocholtz",
            "Bodegraven",
            "Boeicop",
            "Boekel",
            "Boelenslaan",
            "Boerakker",
            "Boesingheliede",
            "Bolsward",
            "Borculo",
            "Borger",
            "Born",
            "Borne",
            "Borsele",
            "Bosch en Duin",
            "Boskoop",
            "Bosschenhoofd",
            "Bourtange",
            "Boven-Hardinxveld",
            "Boven-Leeuwen",
            "Bovenkarspel",
            "Bovensmilde",
            "Boxmeer",
            "Boxtel",
            "Brakel",
            "Breda",
            "Bredevoort",
            "Breezand",
            "Breskens",
            "Breugel",
            "Breukelen",
            "Breukeleveen",
            "Brielle",
            "Briltil",
            "Britsum",
            "Broekhin",
            "Broekhuizen",
            "Broek in Waterland",
            "Broek op Langedijk",
            "Brouwershaven",
            "Bruchem",
            "Brucht",
            "Bruinisse",
            "Brummen",
            "Brunssum",
            "Buchten",
            "Budel",
            "Budel-Dorplein",
            "Budel-Schoot",
            "Buinerveen",
            "Buitenkaag",
            "Buitenpost",
            "Bunde",
            "Bunnik",
            "Bunschoten",
            "Buren",
            "Buren",
            "Burgerveen",
            "Burgum",
            "Burgwerd",
            "Burum",
            "Bussum",
            "Buurse",
            "Cadier en Keer",
            "Cadzand",
            "Callantsoog",
            "Capelle aan den IJssel",
            "Castricum",
            "Centrum",
            "Chaam",
            "Clinge",
            "Coevorden",
            "Colijnsplaat",
            "Colmschate",
            "Craailo",
            "Cromvoirt",
            "Cruquius",
            "Cuijk",
            "Culemborg",
            "Daarle",
            "Dalen",
            "Dalfsen",
            "Damwald",
            "De Bilt",
            "De Blesse",
            "De Cocksdorp",
            "Dedemsvaart",
            "Deest",
            "De Falom",
            "De Glind",
            "De Goorn",
            "De Hoef",
            "De Horst",
            "De Klomp",
            "De Koog",
            "De Kwakel",
            "Delden",
            "Delden",
            "Delfgauw",
            "Delft",
            "Delfzijl",
            "De Lier",
            "De Lutte",
            "De Meern",
            "De Moer",
            "Den Bommel",
            "Den Bosh",
            "Den Burg",
            "Den Deijl",
            "Den Dolder",
            "Den Dungen",
            "Denekamp",
            "Den Haag",
            "Den Helder",
            "Den Hoorn",
            "Den Hout",
            "Den Ilp",
            "Den Oever",
            "De Punt",
            "De Rijp",
            "De Steeg",
            "Deurne",
            "Deventer",
            "De Waal",
            "De Westereen",
            "De Wijk",
            "De Wilp",
            "De Zilk",
            "Didam",
            "Diemen",
            "Diepenheim",
            "Diepenveen",
            "Dieren",
            "Diessen",
            "Dieteren",
            "Diever",
            "Dijk",
            "Dinteloord",
            "Dinxperlo",
            "Dirkshorn",
            "Dirksland",
            "Dodewaard",
            "Doenrade",
            "Doesburg",
            "Doetinchem",
            "Dokkum",
            "Domburg",
            "Dongen",
            "Doorn",
            "Doornenburg",
            "Doornspijk",
            "Doorwerth",
            "Dordrecht",
            "Dorp",
            "Dorst",
            "Drachten",
            "Drempt",
            "Dreumel",
            "Driebergen",
            "Driebruggen",
            "Driehuis",
            "Driel",
            "Driemond",
            "Drogeham",
            "Dronryp",
            "Dronten",
            "Drunen",
            "Druten",
            "Duin",
            "Duiven",
            "Duivendrecht",
            "Dwingeloo",
            "Earnewald",
            "Echt",
            "Echten",
            "Echtenerbrug",
            "Eckart",
            "Edam",
            "Ede",
            "Ederveen",
            "Eede",
            "Eefde",
            "Eelde-Paterswolde",
            "Eelderwolde",
            "Eemnes",
            "Eenrum",
            "Eerbeek",
            "Eersel",
            "Eethen",
            "Eext",
            "Eexterzandvoort",
            "Egchel",
            "Egmond-Binnen",
            "Egmond aan Zee",
            "Eibergen",
            "Eijsden",
            "Eindhoven",
            "Einighausen",
            "Elburg",
            "Ell",
            "Ellecom",
            "Elsendorp",
            "Elsloo",
            "Elst",
            "Elst",
            "Emmeloord",
            "Emmen",
            "Emmer-Compascuum",
            "Emst",
            "Engelen",
            "Enkhuizen",
            "Ens",
            "Enschede",
            "Enschot",
            "Enspijk",
            "Enter",
            "Enumatil",
            "Epe",
            "Epen",
            "Epse",
            "Erica",
            "Erichem",
            "Erm",
            "Ermelo",
            "Erp",
            "Escharen",
            "Espel",
            "Etten",
            "Everdingen",
            "Ewijk",
            "Exloo",
            "Eygelshoven",
            "Eys",
            "Ezinge",
            "Farmsum",
            "Feanwalden",
            "Ferwert",
            "Fijnaart",
            "Finsterwolde",
            "Fleringen",
            "Fluitenberg",
            "Flushing",
            "Foxhol",
            "Franeker",
            "Frederiksoord",
            "Gaanderen",
            "Galder",
            "Gameren",
            "Gapinge",
            "Garderen",
            "Garmerwolde",
            "Garsthuizen",
            "Garyp",
            "Gasselte",
            "Gasselternijveen",
            "Geertruidenberg",
            "Geervliet",
            "Gees",
            "Geesteren",
            "Geesteren",
            "Geldermalsen",
            "Geldrop",
            "Geleen",
            "Gelselaar",
            "Gemeente Rotterdam",
            "Gemert",
            "Gemonde",
            "Genderen",
            "Gendringen",
            "Gendt",
            "Genemuiden",
            "Gennep",
            "Giesbeek",
            "Giessenburg",
            "Giessendam",
            "Gieten",
            "Gieterveen",
            "Giethoorn",
            "Gilze",
            "Glimmen",
            "Goes",
            "Goirle",
            "Goor",
            "Gorinchem",
            "Gorredijk",
            "Gorssel",
            "Gouda",
            "Gouderak",
            "Goudswaard",
            "Goutum",
            "Gramsbergen",
            "Grashoek",
            "Grathem",
            "Grave",
            "Greup",
            "Grijpskerk",
            "Groeningen",
            "Groenlo",
            "Groenveld",
            "Groesbeek",
            "Groessen",
            "Groet",
            "Groningen",
            "Gronsveld",
            "Groot-Agelo",
            "Groot-Ammers",
            "Grootebroek",
            "Grootegast",
            "Grou",
            "Grubbenvorst",
            "Gulpen",
            "Guttecoven",
            "Gytsjerk",
            "Haaften",
            "Haaksbergen",
            "Haalderen",
            "Haamstede",
            "Haaren",
            "Haarle",
            "Haarlem",
            "Haarlemmerliede",
            "Haelen",
            "Halfweg",
            "Halle",
            "Hallum",
            "Halsteren",
            "Hank",
            "Hantum",
            "Hantumhuizen",
            "Hapert",
            "Haps",
            "Hardenberg",
            "Harderwijk",
            "Haren",
            "Haren",
            "Harich",
            "Harkema",
            "Harkstede",
            "Harlingen",
            "Harmelen",
            "Hartwerd",
            "Hasselt",
            "Hattem",
            "Haule",
            "Haulerwijk",
            "Hauwert",
            "Havelte",
            "Hazerswoude-Dorp",
            "Hazerswoude-Rijndijk",
            "Hedel",
            "Hedel",
            "Heeg",
            "Heelsum",
            "Heemskerk",
            "Heemstede",
            "Heenvliet",
            "Heerde",
            "Heerenveen",
            "Heerhugowaard",
            "Heerjansdam",
            "Heerle",
            "Heerlen",
            "Heesch",
            "Heeswijk",
            "Heeswijk-Dinther",
            "Heeten",
            "Heeze",
            "Heijen",
            "Heijningen",
            "Heikant",
            "Heilig Landstichting",
            "Heiloo",
            "Heinenoord",
            "Heino",
            "Hekelingen",
            "Helden",
            "Helenaveen",
            "Hellendoorn",
            "Hellevoetsluis",
            "Hellouw",
            "Helmond",
            "Helvoirt",
            "Hem",
            "Hemelum",
            "Hendrik-Ido-Ambacht",
            "Hengelo",
            "Hengelo",
            "Hengevelde",
            "Hennaard",
            "Hensbroek",
            "Herbaijum",
            "Herkenbosch",
            "Herkingen",
            "Hernen",
            "Herpen",
            "Herten",
            "Herveld",
            "Herwijnen",
            "Heteren",
            "Heukelum",
            "Heusden",
            "Heveadorp",
            "Heythuysen",
            "Hierden",
            "Hijken",
            "Hillegom",
            "Hilvarenbeek",
            "Hilversum",
            "Hindeloopen",
            "Hippolytushoef",
            "Hoedekenskerke",
            "Hoek",
            "Hoek van Holland",
            "Hoenderloo",
            "Hoensbroek",
            "Hoevelaken",
            "Hoge Donk",
            "Hollandsche Rading",
            "Hollandscheveld",
            "Hollum",
            "Holten",
            "Holthees",
            "Holthone",
            "Holtum",
            "Holwierde",
            "Homoet",
            "Honselersdijk",
            "Hoofddorp",
            "Hoofdplaat",
            "Hoogblokland",
            "Hoogeloon",
            "Hoogerheide",
            "Hoogersmilde",
            "Hoogeveen",
            "Hoogezand",
            "Hooge Zwaluwe",
            "Hooghalen",
            "Hoogkarspel",
            "Hoogkerk",
            "Hoogland",
            "Hooglanderveen",
            "Hoogmade",
            "Hoogvliet",
            "Hoogwoud",
            "Hoorn",
            "Hoorn",
            "Hoornaar",
            "Horn",
            "Horst",
            "Hout",
            "Houtakker",
            "Houten",
            "Huijbergen",
            "Huissen",
            "Huis ter Heide",
            "Huizen",
            "Hulsberg",
            "Hulshorst",
            "Hulst",
            "Hummelo",
            "Hurdegaryp",
            "IJhorst",
            "IJlst",
            "IJmuiden",
            "IJsselmuiden",
            "IJsselstein",
            "IJzendijke",
            "IJzendoorn",
            "Ilpendam",
            "Ingelum",
            "Ingen",
            "Ittervoort",
            "Jabeek",
            "Jisp",
            "Joppe",
            "Joure",
            "Jubbega",
            "Julianadorp",
            "Jutrijp",
            "Kaag",
            "Kaatsheuvel",
            "Kalenberg",
            "Kamerik",
            "Kampen",
            "Kamperland",
            "Kantens",
            "Kapelle",
            "Kats",
            "Katwijk",
            "Katwijk aan Zee",
            "Katwoude",
            "Keijenborg",
            "Kekerdom",
            "Keldonk",
            "Kerk-Avezaath",
            "Kerkdriel",
            "Kerkenveld",
            "Kerkrade",
            "Kessel",
            "Kesteren",
            "Kimswerd",
            "Kinderdijk",
            "Klaaswaal",
            "Klazienaveen",
            "Klimmen",
            "Kloetinge",
            "Kloosterhaar",
            "Klundert",
            "Kockengen",
            "Koedijk",
            "Koekange",
            "Koewacht",
            "Kolham",
            "Kolhorn",
            "Kollum",
            "Kommerzijl",
            "Koog aan de Zaan",
            "Kootstertille",
            "Kootwijkerbroek",
            "Kortenhoef",
            "Kortgene",
            "Koudekerk aan den Rijn",
            "Koudekerke",
            "Koudum",
            "Kraggenburg",
            "Krimpen aan de Lek",
            "Krimpen aan den IJssel",
            "Krommenie",
            "Kropswolde",
            "Kruiningen",
            "Kruisland",
            "Kudelstaart",
            "Kuitaart",
            "Kwintsheul",
            "Laag-Soeren",
            "Lage Mierde",
            "Lage Zwaluwe",
            "Landsmeer",
            "Langedijk",
            "Langezwaag",
            "Laren",
            "Lathum",
            "Leek",
            "Leerdam",
            "Leersum",
            "Leeuwarden",
            "Legemeer",
            "Leiden",
            "Leiderdorp",
            "Leidschendam",
            "Leimuiden",
            "Lekkerkerk",
            "Lelystad",
            "Lemele",
            "Lemelerveld",
            "Lemiers",
            "Lemmer",
            "Lent",
            "Lettele",
            "Leusden",
            "Leuth",
            "Lewenborg",
            "Lexmond",
            "Lichtenvoorde",
            "Liempde",
            "Lienden",
            "Lienden",
            "Lies",
            "Lieshout",
            "Liessel",
            "Lievelde",
            "Lijnden",
            "Limbricht",
            "Limmel",
            "Limmen",
            "Linne",
            "Linschoten",
            "Lippenhuizen",
            "Lisse",
            "Lithoijen",
            "Lobith",
            "Lochem",
            "Loenen",
            "Loon op Zand",
            "Loosdrecht",
            "Loozen",
            "Lopik",
            "Loppersum",
            "Losser",
            "Lottum",
            "Lunteren",
            "Lutjebroek",
            "Lutjewinkel",
            "Lutten",
            "Luyksgestel",
            "Maarheeze",
            "Maarn",
            "Maarssen",
            "Maarssenbroek",
            "Maartensdijk",
            "Maasbommel",
            "Maasbracht",
            "Maasbree",
            "Maasdam",
            "Maasdijk",
            "Maashees",
            "Maaskantje",
            "Maasland",
            "Maassluis",
            "Maastricht",
            "Made",
            "Makkum",
            "Malden",
            "Manderveen",
            "Margraten",
            "Marienberg",
            "Markelo",
            "Marknesse",
            "Marrum",
            "Marum",
            "Mastenbroek",
            "Maurik",
            "Mechelen",
            "Medemblik",
            "Meeden",
            "Meer",
            "Meerkerk",
            "Meerlo",
            "Meerssen",
            "Meeuwen",
            "Megchelen",
            "Meijel",
            "Melick",
            "Meppel",
            "Merkelbeek",
            "Merselo",
            "Middelbeers",
            "Middelburg",
            "Middelharnis",
            "Middenbeemster",
            "Middenmeer",
            "Midlum",
            "Mierlo",
            "Mijdrecht",
            "Mijnsheerenland",
            "Mildam",
            "Milheeze",
            "Mill",
            "Millingen",
            "Millingen aan de Rijn",
            "Milsbeek",
            "Moerdijk",
            "Moergestel",
            "Moerkapelle",
            "Molenaarsgraaf",
            "Molenhoek",
            "Molenhoek",
            "Molenschot",
            "Monnickendam",
            "Monster",
            "Montfoort",
            "Montfort",
            "Mook",
            "Mookhoek",
            "Moordrecht",
            "Mortel",
            "Muiden",
            "Muiderberg",
            "Munstergeleen",
            "Muntendam",
            "Mussel",
            "Naaldwijk",
            "Naarden",
            "Nederasselt",
            "Nederhemert",
            "Nederhorst den Berg",
            "Nederweert",
            "Neede",
            "Neer",
            "Neer-Andel",
            "Nes",
            "Netterden",
            "Nibbixwoud",
            "Nieuw-Amsterdam",
            "Nieuw-Balinge",
            "Nieuw-Beijerland",
            "Nieuw-Bergen",
            "Nieuw-Buinen",
            "Nieuw-Dordrecht",
            "Nieuw-Lekkerland",
            "Nieuw-Namen",
            "Nieuw-Schoonebeek",
            "Nieuw-Vennep",
            "Nieuw-Vossemeer",
            "Nieuwdorp",
            "Nieuwe-Niedorp",
            "Nieuwe-Tonge",
            "Nieuwegein",
            "Nieuwehorne",
            "Nieuwendijk",
            "Nieuwe Pekela",
            "Nieuwer-Ter-Aa",
            "Nieuwerbrug",
            "Nieuwerkerk aan den IJssel",
            "Nieuweschoot",
            "Nieuwe Wetering",
            "Nieuwkoop",
            "Nieuwkuijk",
            "Nieuwlande",
            "Nieuwleusen",
            "Nieuwolda",
            "Nieuwpoort",
            "Nieuwstadt",
            "Nieuwveen",
            "Nigtevecht",
            "Nijbroek",
            "Nijhuizum",
            "Nijkerk",
            "Nijkerkerveen",
            "Nijland",
            "Nijmegen",
            "Nijnsel",
            "Nijverdal",
            "Nistelrode",
            "Noardburgum",
            "Noorbeek",
            "Noord-Scharwoude",
            "Noord-Sleen",
            "Noordbroek",
            "Noordeloos",
            "Noorden",
            "Noordgouwe",
            "Noordhorn",
            "Noordlaren",
            "Noordscheschut",
            "Noordwelle",
            "Noordwijk-Binnen",
            "Noordwijk aan Zee",
            "Noordwijkerhout",
            "Noordwolde",
            "Nootdorp",
            "Norg",
            "Nuenen",
            "Nuis",
            "Nuland",
            "Numansdorp",
            "Nunhem",
            "Nunspeet",
            "Nuth",
            "Obbicht",
            "Obdam",
            "Ochten",
            "Odijk",
            "Oeffelt",
            "Oegstgeest",
            "Oene",
            "Oijen",
            "Oirsbeek",
            "Oirschot",
            "Oisterwijk",
            "Oldeberkoop",
            "Oldebroek",
            "Oldeholtpade",
            "Oldehove",
            "Oldekerk",
            "Oldemarkt",
            "Oldenzaal",
            "Olst",
            "Ommen",
            "Onnen",
            "Ooij",
            "Ooltgensplaat",
            "Oost-Souburg",
            "Oostburg",
            "Oostendam",
            "Oosterbeek",
            "Oosterbierum",
            "Oosterend",
            "Oosterhesselen",
            "Oosterhout",
            "Oosterland",
            "Oosternijkerk",
            "Oosterwolde",
            "Oosterwolde",
            "Oosterzee",
            "Oosthuizen",
            "Oostkapelle",
            "Oostvoorne",
            "Oostwold",
            "Oostwoud",
            "Oostzaan",
            "Ootmarsum",
            "Op den Bosch",
            "Opeinde",
            "Ophemert",
            "Opheusden",
            "Opmeer",
            "Oranje",
            "Oranjewoud",
            "Ospel",
            "Oss",
            "Ossendrecht",
            "Oterleek",
            "Otterlo",
            "Ottersum",
            "Oud-Ade",
            "Oud-Alblas",
            "Oud-Beijerland",
            "Oud-Gastel",
            "Oud-Zuilen",
            "Ouddorp",
            "Oude-Tonge",
            "Oudega",
            "Oudehaske",
            "Oudehorne",
            "Oudelande",
            "Oudemirdum",
            "Oudemolen",
            "Oudenbosch",
            "Oudendijk",
            "Oude Pekela",
            "Ouderkerk aan de Amstel",
            "Oudeschild",
            "Oudesluis",
            "Oudewater",
            "Oude Wetering",
            "Oudkarspel",
            "Oudorp",
            "Oudwoude",
            "Overasselt",
            "Overberg",
            "Overdinkel",
            "Overloon",
            "Overveen",
            "Ovezande",
            "Palemig",
            "Pannerden",
            "Panningen",
            "Papekop",
            "Papendrecht",
            "Partij",
            "Paterswolde",
            "Peize",
            "Pernis",
            "Petten",
            "Philippine",
            "Piershil",
            "Pieterburen",
            "Pieterzijl",
            "Pijnacker",
            "Pingjum",
            "Plasmolen",
            "Poeldijk",
            "Poortugaal",
            "Poortvliet",
            "Posterholt",
            "Princenhof",
            "Prinsenbeek",
            "Puiflijk",
            "Purmerend",
            "Purmerland",
            "Puth",
            "Putte",
            "Putten",
            "Puttershoek",
            "Raalte",
            "Raamsdonksveer",
            "Randwijk",
            "Ravenstein",
            "Ravenswoud",
            "Reeuwijk",
            "Rekken",
            "Renesse",
            "Renkum",
            "Renswoude",
            "Ressen",
            "Retranchement",
            "Reusel",
            "Reuver",
            "Rheden",
            "Rhenen",
            "Rhenoy",
            "Rhoon",
            "Ridderkerk",
            "Riethoven",
            "Rietveld",
            "Rijckholt",
            "Rijen",
            "Rijkevoort",
            "Rijnsburg",
            "Rijpwetering",
            "Rijsbergen",
            "Rijsenhout",
            "Rijssen",
            "Rijswijk",
            "Rijswijk",
            "Rilland",
            "Rinsumageast",
            "Rips",
            "Rivierenwijk",
            "Rixtel",
            "Rockanje",
            "Roden",
            "Rodenrijs",
            "Roelofarendsveen",
            "Roermond",
            "Roggel",
            "Rolde",
            "Roodeschool",
            "Roosendaal",
            "Roosteren",
            "Rooth",
            "Rosmalen",
            "Rossum",
            "Rossum",
            "Rotterdam",
            "Rottum",
            "Rottum",
            "Rozenburg",
            "Rozenburg",
            "Rozendaal",
            "Rucphen",
            "Ruinen",
            "Ruinerwold",
            "Rutten",
            "Ruurlo",
            "s-Heerenberg",
            "Saasveld",
            "Sambeek",
            "Santpoort-Noord",
            "Sappemeer",
            "Sassenheim",
            "Sas van Gent",
            "Schagen",
            "Schagerbrug",
            "Schaijk",
            "Schalkhaar",
            "Scharmer",
            "Scheemda",
            "Schellinkhout",
            "Schermerhorn",
            "Scherpenisse",
            "Scherpenzeel",
            "Schiedam",
            "Schiermonnikoog",
            "Schijndel",
            "Schildwolde",
            "Schimmert",
            "Schinnen",
            "Schin op Geul",
            "Schinveld",
            "Schipborg",
            "Schipluiden",
            "Schoondijke",
            "Schoonebeek",
            "Schoonhoven",
            "Schoorl",
            "Schore",
            "Sellingen",
            "Serooskerke",
            "Sevenum",
            "Sibculo",
            "Siddeburen",
            "Siebengewald",
            "Silvolde",
            "Simpelveld",
            "Sint-Michielsgestel",
            "Sint-Oedenrode",
            "Sint Agatha",
            "Sint Annaland",
            "Sint Annaparochie",
            "Sint Anthonis",
            "Sint Hubert",
            "Sint Jansteen",
            "Sintjohannesga",
            "Sint Joost",
            "Sint Maarten",
            "Sint Maartensdijk",
            "Sint Nicolaasga",
            "Sint Odilienberg",
            "Sint Pancras",
            "Sint Philipsland",
            "Sint Willebrord",
            "Sittard",
            "Slagharen",
            "Sleen",
            "Sleeuwijk",
            "Slenaken",
            "Sliedrecht",
            "Slijk-Ewijk",
            "Slochteren",
            "Slootdorp",
            "Sloterdijk",
            "Sluis",
            "Sluiskil",
            "Smilde",
            "Sneek",
            "Soerendonk",
            "Soest",
            "Soesterberg",
            "Someren",
            "Sommelsdijk",
            "Son en Breugel",
            "Spaarndam",
            "Spakenburg",
            "Spanbroek",
            "Spaubeek",
            "Spierdijk",
            "Spijk",
            "Spijkenisse",
            "Sprang",
            "Sprundel",
            "Stad aan 't Haringvliet",
            "Stadskanaal",
            "Stampersgat",
            "Staphorst",
            "Stationsbuurt",
            "Stedum",
            "Steenbergen",
            "Steensel",
            "Steenwijk",
            "Steggerda",
            "Steijl",
            "Stein",
            "Stellendam",
            "Sterksel",
            "Stevensbeek",
            "Stevensweert",
            "Stiens",
            "Stolwijk",
            "Stompetoren",
            "Stompwijk",
            "Stoutenburg",
            "Strijen",
            "Strijensas",
            "Stroe",
            "Stuifzand",
            "Sumar",
            "Surhuisterveen",
            "Surhuizum",
            "Susteren",
            "Suwald",
            "Swalmen",
            "Sweikhuizen",
            "Swifterbant",
            "Taarlo",
            "Tegelen",
            "Ten Boer",
            "Ten Post",
            "Ter Aar",
            "Ter Apel",
            "Ter Apelkanaal",
            "Terblijt",
            "Terborg",
            "Terheijden",
            "Terneuzen",
            "Terschuur",
            "Teteringen",
            "The Hague",
            "Tholen",
            "Tiel",
            "Tienhoven",
            "Tienraij",
            "Tijnje",
            "Tilburg",
            "Tilligte",
            "Tinte",
            "Tjerkwerd",
            "Tolbert",
            "Toldijk",
            "Tolkamer",
            "Tricht",
            "Tubbergen",
            "Tuitjenhorn",
            "Tull",
            "Tweede Exloermond",
            "Tweede Valthermond",
            "Twello",
            "Twijzelerheide",
            "Twisk",
            "Tynaarlo",
            "Tytsjerk",
            "Tzummarum",
            "Uddel",
            "Uden",
            "Udenhout",
            "Ugchelen",
            "Uitdam",
            "Uitgeest",
            "Uithoorn",
            "Uithuizen",
            "Uithuizermeeden",
            "Uitwellingerga",
            "Ulestraten",
            "Ulft",
            "Ulicoten",
            "Ulrum",
            "Ulvenhout",
            "Ureterp",
            "Urk",
            "Urmond",
            "Ursem",
            "Utrecht",
            "Vaals",
            "Vaassen",
            "Valburg",
            "Valkenburg",
            "Valkenburg",
            "Valkenswaard",
            "Valthe",
            "Valthermond",
            "Varik",
            "Varsseveld",
            "Vasse",
            "Veen",
            "Veendam",
            "Veenendaal",
            "Veenhuizen",
            "Veenoord",
            "Veghel",
            "Velddriel",
            "Velden",
            "Veldhoven",
            "Velp",
            "Velsen",
            "Velsen-Noord",
            "Ven-Zelderheide",
            "Venhorst",
            "Venhuizen",
            "Venlo",
            "Venray",
            "Vianen",
            "Vierhouten",
            "Vierlingsbeek",
            "Vierpolders",
            "Vijfhuizen",
            "Vilt",
            "Vinkeveen",
            "Vlaardingen",
            "Vlagtwedde",
            "Vledder",
            "Vleuten",
            "Vlieland",
            "Vlijmen",
            "Vlodrop",
            "Voerendaal",
            "Vogelenzang",
            "Vogelwaarde",
            "Volendam",
            "Volkel",
            "Voorburg",
            "Voorhout",
            "Voorschoten",
            "Voorst",
            "Voorthuizen",
            "Vorden",
            "Vorstenbosch",
            "Vortum-Mullem",
            "Vragender",
            "Vreeland",
            "Vries",
            "Vriezenveen",
            "Vroomshoop",
            "Vrouwenpolder",
            "Vught",
            "Vuren",
            "Waalre",
            "Waalwijk",
            "Waardenburg",
            "Waarder",
            "Waarland",
            "Waddinxveen",
            "Wagenberg",
            "Wagenborgen",
            "Wageningen",
            "Walterswald",
            "Wamel",
            "Wanroij",
            "Wanssum",
            "Wapenveld",
            "Warder",
            "Warffum",
            "Warmenhuizen",
            "Warmond",
            "Warnsveld",
            "Waspik",
            "Wassenaar",
            "Wateringen",
            "Waterland",
            "Weerselo",
            "Weert",
            "Weesp",
            "Wehl",
            "Weidum",
            "Well",
            "Wellerlooi",
            "Wemeldinge",
            "Werkendam",
            "Werkhoven",
            "Wervershoof",
            "Wessem",
            "West-Knollendam",
            "West-Terschelling",
            "Westbeemster",
            "Westbroek",
            "Westdorpe",
            "Westerbork",
            "Westerhaar-Vriezenveensewijk",
            "Westerhoven",
            "Westervoort",
            "Westerwijtwerd",
            "Westkapelle",
            "Westmaas",
            "Westzaan",
            "Weurt",
            "Wezep",
            "Wierden",
            "Wieringerwaard",
            "Wieringerwerf",
            "Wierum",
            "Wijchen",
            "Wijckel",
            "Wijdenes",
            "Wijdewormer",
            "Wijhe",
            "Wijk aan Zee",
            "Wijk bij Duurstede",
            "Wijlre",
            "Wijnaldum",
            "Wijnandsrade",
            "Wijngaarden",
            "Wijster",
            "Wildervank",
            "Willemstad",
            "Wilnis",
            "Wilp",
            "Winkel",
            "Winschoten",
            "Winssen",
            "Winsum",
            "Wintelre",
            "Winterswijk",
            "Wissenkerke",
            "Witharen",
            "Wittem",
            "Witteveen",
            "Woensdrecht",
            "Woerden",
            "Woerdense Verlaat",
            "Wognum",
            "Wolfheze",
            "Wolphaartsdijk",
            "Woltersum",
            "Wolvega",
            "Wommels",
            "Wons",
            "Workum",
            "Wormer",
            "Wormerveer",
            "Woubrugge",
            "Woudenberg",
            "Woudrichem",
            "Woudsend",
            "Wouwsche Plantage",
            "Yde",
            "Yerseke",
            "Ysbrechtum",
            "Zaamslag",
            "Zaandam",
            "Zaandijk",
            "Zaanstad",
            "Zalk",
            "Zaltbommel",
            "Zandeweer",
            "Zandvoort",
            "Zeddam",
            "Zeeland",
            "Zeerijp",
            "Zeewolde",
            "Zeist",
            "Zelhem",
            "Zetten",
            "Zevenaar",
            "Zevenbergen",
            "Zevenbergschen Hoek",
            "Zevenhoven",
            "Zevenhuizen",
            "Zierikzee",
            "Zieuwent",
            "Zijderveld",
            "Zoetermeer",
            "Zoeterwoude",
            "Zonnemaire",
            "Zorgvlied",
            "Zoutelande",
            "Zoutkamp",
            "Zuid-Beijerland",
            "Zuid-Scharwoude",
            "Zuidbroek",
            "Zuidermeer",
            "Zuiderpark",
            "Zuidhorn",
            "Zuidland",
            "Zuidlaren",
            "Zuidoostbeemster",
            "Zuidwolde",
            "Zuidzande",
            "Zuilichem",
            "Zundert",
            "Zutphen",
            "Zwaag",
            "Zwaagdijk-Oost",
            "Zwaanshoek",
            "Zwanenburg",
            "Zwartebroek",
            "Zwartemeer",
            "Zwartewaal",
            "Zwartsluis",
            "Zwijndrecht",
            "Zwinderen",
            "Zwolle"
        ]
    ];

    /**
     * @param string $userRoleName
     * @param string $visibility
     * @return array|null
     */
    public static function selectableFields(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $result = [];

        if (isset(self::$selectableFields['common'][$visibility])) {
            $result = array_merge($result, self::$selectableFields['common'][$visibility]);
        }

        if (isset(self::$selectableFields[$userRoleName][$visibility])) {
            $result = array_merge($result, self::$selectableFields[$userRoleName][$visibility]);
        }

        return (empty($result)) ? null : $result;
    }

    /**
     * @param string $fieldName
     * @param string $userRoleName
     * @param string $arrayManipulationMethodName
     * @return mixed|null
     * @throws \Exception
     */
    public static function selectableField(
        string $fieldName,
        string $userRoleName = 'bot',
        string $arrayManipulationMethodName = ''
    ) {
        $data = self::getSelectableFieldData($fieldName, $userRoleName);

        if ($arrayManipulationMethodName != '') {
            $data = self::applyArrayMethod($arrayManipulationMethodName, $data);
        }

        if (!empty($data)) {
            return $data;
        }

        return null;
    }

    /**
     * @param string $userRoleName
     * @param string $visibility
     * @return array|null
     */
    public static function userTableFields(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $visibilities = ['public', 'private'];

        $result = [];

        if ($visibility == 'all') {
            foreach ($visibilities as $v) {
                if (isset(self::$userTableFields['common'][$v])) {
                    $result = array_merge($result, self::$userTableFields['common'][$v]);
                }

                if (isset(self::$userTableFields[$userRoleName][$v])) {
                    $result = array_merge($result, self::$userTableFields[$userRoleName][$v]);
                }
            }
        } else {
            if (isset(self::$userTableFields['common'][$visibility])) {
                $result = array_merge($result, self::$userTableFields['common'][$visibility]);
            }

            if (isset(self::$userTableFields[$userRoleName][$visibility])) {
                $result = array_merge($result, self::$userTableFields[$userRoleName][$visibility]);
            }
        }

        return (empty($result)) ? null : $result;
    }

    /**
     * @param string $userRoleName
     * @param string $visibility
     * @return array|null
     */
    public static function textFields(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $visibilities = ['public', 'private'];

        $result = [];

        if ($visibility == 'all') {
            foreach ($visibilities as $v) {
                if (isset(self::$textFields['common'][$v])) {
                    $result = array_merge($result, self::$textFields['common'][$v]);
                }

                if (isset(self::$textFields[$userRoleName][$v])) {
                    $result = array_merge($result, self::$textFields[$userRoleName][$v]);
                }

            }
        } else {
            if (isset(self::$textFields['common'][$visibility])) {
                $result = array_merge($result, self::$textFields['common'][$visibility]);
            }

            if (isset(self::$textFields[$userRoleName][$visibility])) {
                $result = array_merge($result, self::$textFields[$userRoleName][$visibility]);
            }
        }

        return (empty($result)) ? null : $result;
    }

    public static function textInputs(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $visibilities = ['public', 'private'];

        $result = [];

        if ($visibility == 'all') {
            foreach ($visibilities as $v) {
                if (isset(self::$textInputs['common'][$v])) {
                    $result = array_merge($result, self::$textInputs['common'][$v]);
                }

                if (isset(self::$textInputs[$userRoleName][$v])) {
                    $result = array_merge($result, self::$textInputs[$userRoleName][$v]);
                }
            }
        } else {
            if (isset(self::$textInputs['common'][$visibility])) {
                $result = array_merge($result, self::$textInputs['common'][$visibility]);
            }

            if (isset(self::$textInputs[$userRoleName][$visibility])) {
                $result = array_merge($result, self::$textInputs[$userRoleName][$visibility]);
            }
        }

        return (empty($result)) ? null : $result;
    }


    /**
     * @param string $userRoleName
     * @return array
     */
    public static function publicFieldNames(string $userRoleName = 'bot')
    {
        return array_merge(
            array_keys(self::selectableFields($userRoleName, 'public')),
            array_keys(self::userTableFields($userRoleName, 'public')),
            self::textFields($userRoleName, 'public'),
            self::textInputs($userRoleName, 'public')
        );
    }

    /**
     * @param string $fieldName
     * @param string $userRoleName
     * @return mixed
     */
    private static function getSelectableFieldData(string $fieldName, string $userRoleName)
    {
        $data = [];

        if (
            isset(self::$selectableFields['common']['public']) &&
            in_array($fieldName, array_keys(self::$selectableFields['common']['public']))
        ) {
            $data = self::$selectableFields['common']['public'][$fieldName];
            return $data;
        } elseif (
            isset(self::$selectableFields[$userRoleName]['public']) &&
            in_array($fieldName, array_keys(self::$selectableFields[$userRoleName]['public']))
        ) {
            $data = self::$selectableFields['common']['public'][$fieldName];
            return $data;
        } elseif (
            isset(self::$selectableFields['common']['private']) &&
            in_array($fieldName, array_keys(self::$selectableFields['common']['private']))
        ) {
            $data = self::$selectableFields['common']['private'][$fieldName];
            return $data;
        } elseif (
            isset(self::$selectableFields[$userRoleName]['private']) &&
            in_array($fieldName, array_keys(self::$selectableFields[$userRoleName]['private']))
        ) {
            $data = self::$selectableFields[$userRoleName]['private'][$fieldName];
            return $data;
        }
        return $data;
    }

    /**
     * @param string $arrayManipulationMethodName
     * @param $data
     * @return mixed
     * @throws \Exception
     */
    private static function applyArrayMethod(string $arrayManipulationMethodName, array $data)
    {
        $allowedArrayManipulations = [
            'array_flip',
            'array_keys',
            'array_values'
        ];

        if (!in_array($arrayManipulationMethodName, $allowedArrayManipulations)) {
            throw new \Exception;
        }

        $data = call_user_func($arrayManipulationMethodName, $data);
        return $data;
    }

    /**
     * @return array
     */
    public static function getCities(string $countryCode = 'nl')
    {
        return self::$cities[$countryCode];
    }
}
