<?php namespace App\Helpers\ApplicationConstants;

/**
 * Class UserConstants
 * @package App\Helpers\ApplicationConstants
 */
class UserConstants
{
    public static $maxAmountOnline = 30;

    public static $ageGroups = [
        '18-25' => '18-25',
        '26-35' => '26-35',
        '36-45' => '36-45',
        '46+' => '46+'
    ];

    public static $radiuses = [
        '20',
        '50',
        '80',
    ];

    public static function getAgeGroups() {
        return self::$ageGroups;
    }

    public static function getRadiuses() {
        return self::$radiuses;
    }


    /**
     * @return int
     */
    public static function getMaxAmountOnline()
    {
        return self::$maxAmountOnline;
    }


    public static $userTableFields = [
        'common' => [
            'public' => [
                'username',
                'first_name',
                'last_name',
                'postal_code',
                'street_name'
            ],
            'private' => [
                'password',
                'account_type',
                'active'
            ],
        ],
        'peasant' => [
            'public' => [
                'email'
            ]
        ]
    ];

    public static $selectableFields = [
        'common' => [
            'public' => [
                'gender' => [
                    1 => 'male',
                    2 => 'female'
                ],
                'looking_for_gender' => [
                    1 => 'male',
                    2 => 'female'
                ],
                'relationship_status' => [
                    1 => 'single',
                    2 => 'in_a_relationship',
                    3 => 'complicated'
                ],
                'body_type' => [
                    1 => 'slender',
                    2 => 'average',
                    3 => 'athletic',
                    4 => 'curvy',
                    5 => 'big'
                ],
                'height' => [
                    1 => '<140',
                    2 => '140-150',
                    3 => '150-160',
                    4 => '160-170',
                    5 => '170-180',
                    6 => '180-190',
                    7 => '190-200',
                    8 => '>200'
                ],
                'eye_color' => [
                    1 => 'green',
                    2 => 'blue',
                    3 => 'brown',
                    4 => 'hazel',
                    5 => 'black'
                ],
                'hair_color' => [
                    1 => 'black',
                    2 => 'grey',
                    3 => 'white',
                    4 => 'brown',
                    5 => 'blond',
                    6 => 'dark_blond',
                    7 => 'red',
                    8 => 'pink'
                ],
                'smoking_habits' => [
                    1 => 'regular',
                    2 => 'social',
                    3 => 'none'
                ],
                'drinking_habits' => [
                    1 => 'regular',
                    2 => 'social',
                    3 => 'none'
                ]
            ],
            'private' => [
                'role' => [
                    1 => 'admin',
                    2 => 'peasant',
                    3 => 'bot',
                    4 => 'operator',
                    5 => 'editor'
                ],
                'account_type' => [
                    1 => 'free',
                    2 => 'small',
                    3 => 'medium',
                    4 => 'large',
                ]
            ]
        ],
        'bot' => [
            'private' => [
                'category' => [
                    1 => 'seniors',
                    2 => 'teens',
                    3 => 'naked',
                    4 => 'dressed',
                ]
            ],
        ]
    ];

    public static $textFields = [
        'common' => [
            'public' => [
                'about_me'
            ]
        ]
    ];

    public static $textInputs = [
        'common' => [
            'public' => [
                'dob',
                'city',
                'country'
            ],
            'private' => [
                'lat',
                'lng'
            ]
        ]
    ];

    public static $immutableFields = [
        'gender'
    ];

    public static $cities = [
        'nl' => [
            "'s-Graveland (nl)",
            "'s-Gravendeel (nl)",
            "'s-Gravenpolder (nl)",
            "'s-Gravenzande (nl)",
            "'s-Heer-Hendrikskinderen (nl)",
            "'s-Heerenhoek (nl)",
            "'s-Hertogenbosch (nl)",
            "'s Gravenmoer (nl)",
            "'t Harde (nl)",
            "'t Kabel (nl)",
            "'t Zand (nl)",
            "Aagtekerke (nl)",
            "Aalburg (nl)",
            "Aalden (nl)",
            "Aalsmeer (nl)",
            "Aalsmeerderbrug (nl)",
            "Aalst (nl)",
            "Aalten (nl)",
            "Aardenburg (nl)",
            "Abbekerk (nl)",
            "Abbenes (nl)",
            "Abcoude (nl)",
            "Achterberg (nl)",
            "Achterveld (nl)",
            "Achthuizen (nl)",
            "Achtmaal (nl)",
            "Aduard (nl)",
            "Aerdenhout (nl)",
            "Aerdt (nl)",
            "Afferden (nl)",
            "Akersloot (nl)",
            "Akkrum (nl)",
            "Albergen (nl)",
            "Alblasserdam (nl)",
            "Alde Leie (nl)",
            "Alem (nl)",
            "Alkmaar (nl)",
            "Almelo (nl)",
            "Almere (nl)",
            "Almere Haven (nl)",
            "Almkerk (nl)",
            "Alphen (nl)",
            "Alphen aan den Rijn (nl)",
            "Ameide (nl)",
            "America (nl)",
            "Amerongen (nl)",
            "Amersfoort (nl)",
            "Ammerstol (nl)",
            "Ammerzoden (nl)",
            "Amstelhoek (nl)",
            "Amstelveen (nl)",
            "Amstenrade (nl)",
            "Amsterdam (nl)",
            "Anderen (nl)",
            "Andijk (nl)",
            "Ane (nl)",
            "Angeren (nl)",
            "Anjum (nl)",
            "Ankeveen (nl)",
            "Anloo (nl)",
            "Anna Paulowna (nl)",
            "Annen (nl)",
            "Apeldoorn (nl)",
            "Appelscha (nl)",
            "Appeltern (nl)",
            "Appingedam (nl)",
            "Arcen (nl)",
            "Arkel (nl)",
            "Arnemuiden (nl)",
            "Arnhem (nl)",
            "Asperen (nl)",
            "Assen (nl)",
            "Assendelft (nl)",
            "Asten (nl)",
            "Augustinusga (nl)",
            "Avenhorn (nl)",
            "Axel (nl)",
            "Baambrugge (nl)",
            "Baarland (nl)",
            "Baarle-Nassau (nl)",
            "Baarlo (nl)",
            "Baarn (nl)",
            "Baars (nl)",
            "Babberich (nl)",
            "Badhoevedorp (nl)",
            "Baexem (nl)",
            "Bakel (nl)",
            "Baken (nl)",
            "Bakhuizen (nl)",
            "Balgoij (nl)",
            "Balk (nl)",
            "Ballum (nl)",
            "Banholt (nl)",
            "Barchem (nl)",
            "Barendrecht (nl)",
            "Barneveld (nl)",
            "Batenburg (nl)",
            "Bathmen (nl)",
            "Bavel (nl)",
            "Bedum (nl)",
            "Beegden (nl)",
            "Beek (nl)",
            "Beek (nl)",
            "Beek (nl)",
            "Beekbergen (nl)",
            "Beerta (nl)",
            "Beerzerveld (nl)",
            "Beesd (nl)",
            "Beesel (nl)",
            "Beets (nl)",
            "Beetsterzwaag (nl)",
            "Beilen (nl)",
            "Beinsdorp (nl)",
            "Belfeld (nl)",
            "Bellingwolde (nl)",
            "Bemelen (nl)",
            "Bemmel (nl)",
            "Beneden-Leeuwen (nl)",
            "Bennebroek (nl)",
            "Bennekom (nl)",
            "Benningbroek (nl)",
            "Benthuizen (nl)",
            "Berg (nl)",
            "Bergambacht (nl)",
            "Bergeijk (nl)",
            "Bergen (nl)",
            "Bergen (nl)",
            "Berg en Dal (nl)",
            "Bergen op Zoom (nl)",
            "Bergentheim (nl)",
            "Bergharen (nl)",
            "Berghem (nl)",
            "Bergschenhoek (nl)",
            "Beringe (nl)",
            "Berkenwoude (nl)",
            "Berkhout (nl)",
            "Berlicum (nl)",
            "Best (nl)",
            "Beugen (nl)",
            "Beuningen (nl)",
            "Beusichem (nl)",
            "Beverwijk (nl)",
            "Biddinghuizen (nl)",
            "Bierum (nl)",
            "Biervliet (nl)",
            "Biest (nl)",
            "Bilthoven (nl)",
            "Bitgum (nl)",
            "Bladel (nl)",
            "Blaricum (nl)",
            "Bleiswijk (nl)",
            "Blerick (nl)",
            "Bleskensgraaf (nl)",
            "Blitterswijck (nl)",
            "Bloemendaal (nl)",
            "Blokker (nl)",
            "Blokzijl (nl)",
            "Bocholtz (nl)",
            "Bodegraven (nl)",
            "Boeicop (nl)",
            "Boekel (nl)",
            "Boelenslaan (nl)",
            "Boerakker (nl)",
            "Boesingheliede (nl)",
            "Bolsward (nl)",
            "Borculo (nl)",
            "Borger (nl)",
            "Born (nl)",
            "Borne (nl)",
            "Borsele (nl)",
            "Bosch en Duin (nl)",
            "Boskoop (nl)",
            "Bosschenhoofd (nl)",
            "Bourtange (nl)",
            "Boven-Hardinxveld (nl)",
            "Boven-Leeuwen (nl)",
            "Bovenkarspel (nl)",
            "Bovensmilde (nl)",
            "Boxmeer (nl)",
            "Boxtel (nl)",
            "Brakel (nl)",
            "Breda (nl)",
            "Bredevoort (nl)",
            "Breezand (nl)",
            "Breskens (nl)",
            "Breugel (nl)",
            "Breukelen (nl)",
            "Breukeleveen (nl)",
            "Brielle (nl)",
            "Briltil (nl)",
            "Britsum (nl)",
            "Broekhin (nl)",
            "Broekhuizen (nl)",
            "Broek in Waterland (nl)",
            "Broek op Langedijk (nl)",
            "Brouwershaven (nl)",
            "Bruchem (nl)",
            "Brucht (nl)",
            "Bruinisse (nl)",
            "Brummen (nl)",
            "Brunssum (nl)",
            "Buchten (nl)",
            "Budel (nl)",
            "Budel-Dorplein (nl)",
            "Budel-Schoot (nl)",
            "Buinerveen (nl)",
            "Buitenkaag (nl)",
            "Buitenpost (nl)",
            "Bunde (nl)",
            "Bunnik (nl)",
            "Bunschoten (nl)",
            "Buren (nl)",
            "Buren (nl)",
            "Burgerveen (nl)",
            "Burgum (nl)",
            "Burgwerd (nl)",
            "Burum (nl)",
            "Bussum (nl)",
            "Buurse (nl)",
            "Cadier en Keer (nl)",
            "Cadzand (nl)",
            "Callantsoog (nl)",
            "Capelle aan den IJssel (nl)",
            "Castricum (nl)",
            "Centrum (nl)",
            "Chaam (nl)",
            "Clinge (nl)",
            "Coevorden (nl)",
            "Colijnsplaat (nl)",
            "Colmschate (nl)",
            "Craailo (nl)",
            "Cromvoirt (nl)",
            "Cruquius (nl)",
            "Cuijk (nl)",
            "Culemborg (nl)",
            "Daarle (nl)",
            "Dalen (nl)",
            "Dalfsen (nl)",
            "Damwald (nl)",
            "De Bilt (nl)",
            "De Blesse (nl)",
            "De Cocksdorp (nl)",
            "Dedemsvaart (nl)",
            "Deest (nl)",
            "De Falom (nl)",
            "De Glind (nl)",
            "De Goorn (nl)",
            "De Hoef (nl)",
            "De Horst (nl)",
            "De Klomp (nl)",
            "De Koog (nl)",
            "De Kwakel (nl)",
            "Delden (nl)",
            "Delden (nl)",
            "Delfgauw (nl)",
            "Delft (nl)",
            "Delfzijl (nl)",
            "De Lier (nl)",
            "De Lutte (nl)",
            "De Meern (nl)",
            "De Moer (nl)",
            "Den Bommel (nl)",
            "Den Bosch (nl)",
            "Den Burg (nl)",
            "Den Deijl (nl)",
            "Den Dolder (nl)",
            "Den Dungen (nl)",
            "Denekamp (nl)",
            "Den Haag (nl)",
            "Den Helder (nl)",
            "Den Hoorn (nl)",
            "Den Hout (nl)",
            "Den Ilp (nl)",
            "Den Oever (nl)",
            "De Punt (nl)",
            "De Rijp (nl)",
            "De Steeg (nl)",
            "Deurne (nl)",
            "Deventer (nl)",
            "De Waal (nl)",
            "De Westereen (nl)",
            "De Wijk (nl)",
            "De Wilp (nl)",
            "De Zilk (nl)",
            "Didam (nl)",
            "Diemen (nl)",
            "Diepenheim (nl)",
            "Diepenveen (nl)",
            "Dieren (nl)",
            "Diessen (nl)",
            "Dieteren (nl)",
            "Diever (nl)",
            "Dijk (nl)",
            "Dinteloord (nl)",
            "Dinxperlo (nl)",
            "Dirkshorn (nl)",
            "Dirksland (nl)",
            "Dodewaard (nl)",
            "Doenrade (nl)",
            "Doesburg (nl)",
            "Doetinchem (nl)",
            "Dokkum (nl)",
            "Domburg (nl)",
            "Dongen (nl)",
            "Doorn (nl)",
            "Doornenburg (nl)",
            "Doornspijk (nl)",
            "Doorwerth (nl)",
            "Dordrecht (nl)",
            "Dorp (nl)",
            "Dorst (nl)",
            "Drachten (nl)",
            "Drempt (nl)",
            "Dreumel (nl)",
            "Driebergen (nl)",
            "Driebruggen (nl)",
            "Driehuis (nl)",
            "Driel (nl)",
            "Driemond (nl)",
            "Drogeham (nl)",
            "Dronryp (nl)",
            "Dronten (nl)",
            "Drunen (nl)",
            "Druten (nl)",
            "Duin (nl)",
            "Duiven (nl)",
            "Duivendrecht (nl)",
            "Dwingeloo (nl)",
            "Earnewald (nl)",
            "Echt (nl)",
            "Echten (nl)",
            "Echtenerbrug (nl)",
            "Eckart (nl)",
            "Edam (nl)",
            "Ede (nl)",
            "Ederveen (nl)",
            "Eede (nl)",
            "Eefde (nl)",
            "Eelde-Paterswolde (nl)",
            "Eelderwolde (nl)",
            "Eemnes (nl)",
            "Eenrum (nl)",
            "Eerbeek (nl)",
            "Eersel (nl)",
            "Eethen (nl)",
            "Eext (nl)",
            "Eexterzandvoort (nl)",
            "Egchel (nl)",
            "Egmond-Binnen (nl)",
            "Egmond aan Zee (nl)",
            "Eibergen (nl)",
            "Eijsden (nl)",
            "Eindhoven (nl)",
            "Einighausen (nl)",
            "Elburg (nl)",
            "Ell (nl)",
            "Ellecom (nl)",
            "Elsendorp (nl)",
            "Elsloo (nl)",
            "Elst (nl)",
            "Elst (nl)",
            "Emmeloord (nl)",
            "Emmen (nl)",
            "Emmer-Compascuum (nl)",
            "Emst (nl)",
            "Engelen (nl)",
            "Enkhuizen (nl)",
            "Ens (nl)",
            "Enschede (nl)",
            "Enschot (nl)",
            "Enspijk (nl)",
            "Enter (nl)",
            "Enumatil (nl)",
            "Epe (nl)",
            "Epen (nl)",
            "Epse (nl)",
            "Erica (nl)",
            "Erichem (nl)",
            "Erm (nl)",
            "Ermelo (nl)",
            "Erp (nl)",
            "Escharen (nl)",
            "Espel (nl)",
            "Etten (nl)",
            "Everdingen (nl)",
            "Ewijk (nl)",
            "Exloo (nl)",
            "Eygelshoven (nl)",
            "Eys (nl)",
            "Ezinge (nl)",
            "Farmsum (nl)",
            "Feanwalden (nl)",
            "Ferwert (nl)",
            "Fijnaart (nl)",
            "Finsterwolde (nl)",
            "Fleringen (nl)",
            "Fluitenberg (nl)",
            "Flushing (nl)",
            "Foxhol (nl)",
            "Franeker (nl)",
            "Frederiksoord (nl)",
            "Gaanderen (nl)",
            "Galder (nl)",
            "Gameren (nl)",
            "Gapinge (nl)",
            "Garderen (nl)",
            "Garmerwolde (nl)",
            "Garsthuizen (nl)",
            "Garyp (nl)",
            "Gasselte (nl)",
            "Gasselternijveen (nl)",
            "Geertruidenberg (nl)",
            "Geervliet (nl)",
            "Gees (nl)",
            "Geesteren (nl)",
            "Geesteren (nl)",
            "Geldermalsen (nl)",
            "Geldrop (nl)",
            "Geleen (nl)",
            "Gelselaar (nl)",
            "Gemeente Rotterdam (nl)",
            "Gemert (nl)",
            "Gemonde (nl)",
            "Genderen (nl)",
            "Gendringen (nl)",
            "Gendt (nl)",
            "Genemuiden (nl)",
            "Gennep (nl)",
            "Giesbeek (nl)",
            "Giessenburg (nl)",
            "Giessendam (nl)",
            "Gieten (nl)",
            "Gieterveen (nl)",
            "Giethoorn (nl)",
            "Gilze (nl)",
            "Glimmen (nl)",
            "Goes (nl)",
            "Goirle (nl)",
            "Goor (nl)",
            "Gorinchem (nl)",
            "Gorredijk (nl)",
            "Gorssel (nl)",
            "Gouda (nl)",
            "Gouderak (nl)",
            "Goudswaard (nl)",
            "Goutum (nl)",
            "Gramsbergen (nl)",
            "Grashoek (nl)",
            "Grathem (nl)",
            "Grave (nl)",
            "Greup (nl)",
            "Grijpskerk (nl)",
            "Groeningen (nl)",
            "Groenlo (nl)",
            "Groenveld (nl)",
            "Groesbeek (nl)",
            "Groessen (nl)",
            "Groet (nl)",
            "Groningen (nl)",
            "Gronsveld (nl)",
            "Groot-Agelo (nl)",
            "Groot-Ammers (nl)",
            "Grootebroek (nl)",
            "Grootegast (nl)",
            "Grou (nl)",
            "Grubbenvorst (nl)",
            "Gulpen (nl)",
            "Guttecoven (nl)",
            "Gytsjerk (nl)",
            "Haaften (nl)",
            "Haaksbergen (nl)",
            "Haalderen (nl)",
            "Haamstede (nl)",
            "Haaren (nl)",
            "Haarle (nl)",
            "Haarlem (nl)",
            "Haarlemmerliede (nl)",
            "Haelen (nl)",
            "Halfweg (nl)",
            "Halle (nl)",
            "Hallum (nl)",
            "Halsteren (nl)",
            "Hank (nl)",
            "Hantum (nl)",
            "Hantumhuizen (nl)",
            "Hapert (nl)",
            "Haps (nl)",
            "Hardenberg (nl)",
            "Harderwijk (nl)",
            "Haren (nl)",
            "Haren (nl)",
            "Harich (nl)",
            "Harkema (nl)",
            "Harkstede (nl)",
            "Harlingen (nl)",
            "Harmelen (nl)",
            "Hartwerd (nl)",
            "Hasselt (nl)",
            "Hattem (nl)",
            "Haule (nl)",
            "Haulerwijk (nl)",
            "Hauwert (nl)",
            "Havelte (nl)",
            "Hazerswoude-Dorp (nl)",
            "Hazerswoude-Rijndijk (nl)",
            "Hedel (nl)",
            "Hedel (nl)",
            "Heeg (nl)",
            "Heelsum (nl)",
            "Heemskerk (nl)",
            "Heemstede (nl)",
            "Heenvliet (nl)",
            "Heerde (nl)",
            "Heerenveen (nl)",
            "Heerhugowaard (nl)",
            "Heerjansdam (nl)",
            "Heerle (nl)",
            "Heerlen (nl)",
            "Heesch (nl)",
            "Heeswijk (nl)",
            "Heeswijk-Dinther (nl)",
            "Heeten (nl)",
            "Heeze (nl)",
            "Heijen (nl)",
            "Heijningen (nl)",
            "Heikant (nl)",
            "Heilig Landstichting (nl)",
            "Heiloo (nl)",
            "Heinenoord (nl)",
            "Heino (nl)",
            "Hekelingen (nl)",
            "Helden (nl)",
            "Helenaveen (nl)",
            "Hellendoorn (nl)",
            "Hellevoetsluis (nl)",
            "Hellouw (nl)",
            "Helmond (nl)",
            "Helvoirt (nl)",
            "Hem (nl)",
            "Hemelum (nl)",
            "Hendrik-Ido-Ambacht (nl)",
            "Hengelo (nl)",
            "Hengelo (nl)",
            "Hengevelde (nl)",
            "Hennaard (nl)",
            "Hensbroek (nl)",
            "Herbaijum (nl)",
            "Herkenbosch (nl)",
            "Herkingen (nl)",
            "Hernen (nl)",
            "Herpen (nl)",
            "Herten (nl)",
            "Herveld (nl)",
            "Herwijnen (nl)",
            "Heteren (nl)",
            "Heukelum (nl)",
            "Heusden (nl)",
            "Heveadorp (nl)",
            "Heythuysen (nl)",
            "Hierden (nl)",
            "Hijken (nl)",
            "Hillegom (nl)",
            "Hilvarenbeek (nl)",
            "Hilversum (nl)",
            "Hindeloopen (nl)",
            "Hippolytushoef (nl)",
            "Hoedekenskerke (nl)",
            "Hoek (nl)",
            "Hoek van Holland (nl)",
            "Hoenderloo (nl)",
            "Hoensbroek (nl)",
            "Hoevelaken (nl)",
            "Hoge Donk (nl)",
            "Hollandsche Rading (nl)",
            "Hollandscheveld (nl)",
            "Hollum (nl)",
            "Holten (nl)",
            "Holthees (nl)",
            "Holthone (nl)",
            "Holtum (nl)",
            "Holwierde (nl)",
            "Homoet (nl)",
            "Honselersdijk (nl)",
            "Hoofddorp (nl)",
            "Hoofdplaat (nl)",
            "Hoogblokland (nl)",
            "Hoogeloon (nl)",
            "Hoogerheide (nl)",
            "Hoogersmilde (nl)",
            "Hoogeveen (nl)",
            "Hoogezand (nl)",
            "Hooge Zwaluwe (nl)",
            "Hooghalen (nl)",
            "Hoogkarspel (nl)",
            "Hoogkerk (nl)",
            "Hoogland (nl)",
            "Hooglanderveen (nl)",
            "Hoogmade (nl)",
            "Hoogvliet (nl)",
            "Hoogwoud (nl)",
            "Hoorn (nl)",
            "Hoorn (nl)",
            "Hoornaar (nl)",
            "Horn (nl)",
            "Horst (nl)",
            "Hout (nl)",
            "Houtakker (nl)",
            "Houten (nl)",
            "Huijbergen (nl)",
            "Huissen (nl)",
            "Huis ter Heide (nl)",
            "Huizen (nl)",
            "Hulsberg (nl)",
            "Hulshorst (nl)",
            "Hulst (nl)",
            "Hummelo (nl)",
            "Hurdegaryp (nl)",
            "IJhorst (nl)",
            "IJlst (nl)",
            "IJmuiden (nl)",
            "IJsselmuiden (nl)",
            "IJsselstein (nl)",
            "IJzendijke (nl)",
            "IJzendoorn (nl)",
            "Ilpendam (nl)",
            "Ingelum (nl)",
            "Ingen (nl)",
            "Ittervoort (nl)",
            "Jabeek (nl)",
            "Jisp (nl)",
            "Joppe (nl)",
            "Joure (nl)",
            "Jubbega (nl)",
            "Julianadorp (nl)",
            "Jutrijp (nl)",
            "Kaag (nl)",
            "Kaatsheuvel (nl)",
            "Kalenberg (nl)",
            "Kamerik (nl)",
            "Kampen (nl)",
            "Kamperland (nl)",
            "Kantens (nl)",
            "Kapelle (nl)",
            "Kats (nl)",
            "Katwijk (nl)",
            "Katwijk aan Zee (nl)",
            "Katwoude (nl)",
            "Keijenborg (nl)",
            "Kekerdom (nl)",
            "Keldonk (nl)",
            "Kerk-Avezaath (nl)",
            "Kerkdriel (nl)",
            "Kerkenveld (nl)",
            "Kerkrade (nl)",
            "Kessel (nl)",
            "Kesteren (nl)",
            "Kimswerd (nl)",
            "Kinderdijk (nl)",
            "Klaaswaal (nl)",
            "Klazienaveen (nl)",
            "Klimmen (nl)",
            "Kloetinge (nl)",
            "Kloosterhaar (nl)",
            "Klundert (nl)",
            "Kockengen (nl)",
            "Koedijk (nl)",
            "Koekange (nl)",
            "Koewacht (nl)",
            "Kolham (nl)",
            "Kolhorn (nl)",
            "Kollum (nl)",
            "Kommerzijl (nl)",
            "Koog aan de Zaan (nl)",
            "Kootstertille (nl)",
            "Kootwijkerbroek (nl)",
            "Kortenhoef (nl)",
            "Kortgene (nl)",
            "Koudekerk aan den Rijn (nl)",
            "Koudekerke (nl)",
            "Koudum (nl)",
            "Kraggenburg (nl)",
            "Krimpen aan de Lek (nl)",
            "Krimpen aan den IJssel (nl)",
            "Krommenie (nl)",
            "Kropswolde (nl)",
            "Kruiningen (nl)",
            "Kruisland (nl)",
            "Kudelstaart (nl)",
            "Kuitaart (nl)",
            "Kwintsheul (nl)",
            "Laag-Soeren (nl)",
            "Lage Mierde (nl)",
            "Lage Zwaluwe (nl)",
            "Landsmeer (nl)",
            "Langedijk (nl)",
            "Langezwaag (nl)",
            "Laren (nl)",
            "Lathum (nl)",
            "Leek (nl)",
            "Leerdam (nl)",
            "Leersum (nl)",
            "Leeuwarden (nl)",
            "Legemeer (nl)",
            "Leiden (nl)",
            "Leiderdorp (nl)",
            "Leidschendam (nl)",
            "Leimuiden (nl)",
            "Lekkerkerk (nl)",
            "Lelystad (nl)",
            "Lemele (nl)",
            "Lemelerveld (nl)",
            "Lemiers (nl)",
            "Lemmer (nl)",
            "Lent (nl)",
            "Lettele (nl)",
            "Leusden (nl)",
            "Leuth (nl)",
            "Lewenborg (nl)",
            "Lexmond (nl)",
            "Lichtenvoorde (nl)",
            "Liempde (nl)",
            "Lienden (nl)",
            "Lienden (nl)",
            "Lies (nl)",
            "Lieshout (nl)",
            "Liessel (nl)",
            "Lievelde (nl)",
            "Lijnden (nl)",
            "Limbricht (nl)",
            "Limmel (nl)",
            "Limmen (nl)",
            "Linne (nl)",
            "Linschoten (nl)",
            "Lippenhuizen (nl)",
            "Lisse (nl)",
            "Lithoijen (nl)",
            "Lobith (nl)",
            "Lochem (nl)",
            "Loenen (nl)",
            "Loon op Zand (nl)",
            "Loosdrecht (nl)",
            "Loozen (nl)",
            "Lopik (nl)",
            "Loppersum (nl)",
            "Losser (nl)",
            "Lottum (nl)",
            "Lunteren (nl)",
            "Lutjebroek (nl)",
            "Lutjewinkel (nl)",
            "Lutten (nl)",
            "Luyksgestel (nl)",
            "Maarheeze (nl)",
            "Maarn (nl)",
            "Maarssen (nl)",
            "Maarssenbroek (nl)",
            "Maartensdijk (nl)",
            "Maasbommel (nl)",
            "Maasbracht (nl)",
            "Maasbree (nl)",
            "Maasdam (nl)",
            "Maasdijk (nl)",
            "Maashees (nl)",
            "Maaskantje (nl)",
            "Maasland (nl)",
            "Maassluis (nl)",
            "Maastricht (nl)",
            "Made (nl)",
            "Makkum (nl)",
            "Malden (nl)",
            "Manderveen (nl)",
            "Margraten (nl)",
            "Marienberg (nl)",
            "Markelo (nl)",
            "Marknesse (nl)",
            "Marrum (nl)",
            "Marum (nl)",
            "Mastenbroek (nl)",
            "Maurik (nl)",
            "Mechelen (nl)",
            "Medemblik (nl)",
            "Meeden (nl)",
            "Meer (nl)",
            "Meerkerk (nl)",
            "Meerlo (nl)",
            "Meerssen (nl)",
            "Meeuwen (nl)",
            "Megchelen (nl)",
            "Meijel (nl)",
            "Melick (nl)",
            "Meppel (nl)",
            "Merkelbeek (nl)",
            "Merselo (nl)",
            "Middelbeers (nl)",
            "Middelburg (nl)",
            "Middelharnis (nl)",
            "Middenbeemster (nl)",
            "Middenmeer (nl)",
            "Midlum (nl)",
            "Mierlo (nl)",
            "Mijdrecht (nl)",
            "Mijnsheerenland (nl)",
            "Mildam (nl)",
            "Milheeze (nl)",
            "Mill (nl)",
            "Millingen (nl)",
            "Millingen aan de Rijn (nl)",
            "Milsbeek (nl)",
            "Moerdijk (nl)",
            "Moergestel (nl)",
            "Moerkapelle (nl)",
            "Molenaarsgraaf (nl)",
            "Molenhoek (nl)",
            "Molenhoek (nl)",
            "Molenschot (nl)",
            "Monnickendam (nl)",
            "Monster (nl)",
            "Montfoort (nl)",
            "Montfort (nl)",
            "Mook (nl)",
            "Mookhoek (nl)",
            "Moordrecht (nl)",
            "Mortel (nl)",
            "Muiden (nl)",
            "Muiderberg (nl)",
            "Munstergeleen (nl)",
            "Muntendam (nl)",
            "Mussel (nl)",
            "Naaldwijk (nl)",
            "Naarden (nl)",
            "Nederasselt (nl)",
            "Nederhemert (nl)",
            "Nederhorst den Berg (nl)",
            "Nederweert (nl)",
            "Neede (nl)",
            "Neer (nl)",
            "Neer-Andel (nl)",
            "Nes (nl)",
            "Netterden (nl)",
            "Nibbixwoud (nl)",
            "Nieuw-Amsterdam (nl)",
            "Nieuw-Balinge (nl)",
            "Nieuw-Beijerland (nl)",
            "Nieuw-Bergen (nl)",
            "Nieuw-Buinen (nl)",
            "Nieuw-Dordrecht (nl)",
            "Nieuw-Lekkerland (nl)",
            "Nieuw-Namen (nl)",
            "Nieuw-Schoonebeek (nl)",
            "Nieuw-Vennep (nl)",
            "Nieuw-Vossemeer (nl)",
            "Nieuwdorp (nl)",
            "Nieuwe-Niedorp (nl)",
            "Nieuwe-Tonge (nl)",
            "Nieuwegein (nl)",
            "Nieuwehorne (nl)",
            "Nieuwendijk (nl)",
            "Nieuwe Pekela (nl)",
            "Nieuwer-Ter-Aa (nl)",
            "Nieuwerbrug (nl)",
            "Nieuwerkerk aan den IJssel (nl)",
            "Nieuweschoot (nl)",
            "Nieuwe Wetering (nl)",
            "Nieuwkoop (nl)",
            "Nieuwkuijk (nl)",
            "Nieuwlande (nl)",
            "Nieuwleusen (nl)",
            "Nieuwolda (nl)",
            "Nieuwpoort (nl)",
            "Nieuwstadt (nl)",
            "Nieuwveen (nl)",
            "Nigtevecht (nl)",
            "Nijbroek (nl)",
            "Nijhuizum (nl)",
            "Nijkerk (nl)",
            "Nijkerkerveen (nl)",
            "Nijland (nl)",
            "Nijmegen (nl)",
            "Nijnsel (nl)",
            "Nijverdal (nl)",
            "Nistelrode (nl)",
            "Noardburgum (nl)",
            "Noorbeek (nl)",
            "Noord-Scharwoude (nl)",
            "Noord-Sleen (nl)",
            "Noordbroek (nl)",
            "Noordeloos (nl)",
            "Noorden (nl)",
            "Noordgouwe (nl)",
            "Noordhorn (nl)",
            "Noordlaren (nl)",
            "Noordscheschut (nl)",
            "Noordwelle (nl)",
            "Noordwijk-Binnen (nl)",
            "Noordwijk aan Zee (nl)",
            "Noordwijkerhout (nl)",
            "Noordwolde (nl)",
            "Nootdorp (nl)",
            "Norg (nl)",
            "Nuenen (nl)",
            "Nuis (nl)",
            "Nuland (nl)",
            "Numansdorp (nl)",
            "Nunhem (nl)",
            "Nunspeet (nl)",
            "Nuth (nl)",
            "Obbicht (nl)",
            "Obdam (nl)",
            "Ochten (nl)",
            "Odijk (nl)",
            "Oeffelt (nl)",
            "Oegstgeest (nl)",
            "Oene (nl)",
            "Oijen (nl)",
            "Oirsbeek (nl)",
            "Oirschot (nl)",
            "Oisterwijk (nl)",
            "Oldeberkoop (nl)",
            "Oldebroek (nl)",
            "Oldeholtpade (nl)",
            "Oldehove (nl)",
            "Oldekerk (nl)",
            "Oldemarkt (nl)",
            "Oldenzaal (nl)",
            "Olst (nl)",
            "Ommen (nl)",
            "Onnen (nl)",
            "Ooij (nl)",
            "Ooltgensplaat (nl)",
            "Oost-Souburg (nl)",
            "Oostburg (nl)",
            "Oostendam (nl)",
            "Oosterbeek (nl)",
            "Oosterbierum (nl)",
            "Oosterend (nl)",
            "Oosterhesselen (nl)",
            "Oosterhout (nl)",
            "Oosterland (nl)",
            "Oosternijkerk (nl)",
            "Oosterwolde (nl)",
            "Oosterwolde (nl)",
            "Oosterzee (nl)",
            "Oosthuizen (nl)",
            "Oostkapelle (nl)",
            "Oostvoorne (nl)",
            "Oostwold (nl)",
            "Oostwoud (nl)",
            "Oostzaan (nl)",
            "Ootmarsum (nl)",
            "Op den Bosch (nl)",
            "Opeinde (nl)",
            "Ophemert (nl)",
            "Opheusden (nl)",
            "Opmeer (nl)",
            "Oranje (nl)",
            "Oranjewoud (nl)",
            "Ospel (nl)",
            "Oss (nl)",
            "Ossendrecht (nl)",
            "Oterleek (nl)",
            "Otterlo (nl)",
            "Ottersum (nl)",
            "Oud-Ade (nl)",
            "Oud-Alblas (nl)",
            "Oud-Beijerland (nl)",
            "Oud-Gastel (nl)",
            "Oud-Zuilen (nl)",
            "Ouddorp (nl)",
            "Oude-Tonge (nl)",
            "Oudega (nl)",
            "Oudehaske (nl)",
            "Oudehorne (nl)",
            "Oudelande (nl)",
            "Oudemirdum (nl)",
            "Oudemolen (nl)",
            "Oudenbosch (nl)",
            "Oudendijk (nl)",
            "Oude Pekela (nl)",
            "Ouderkerk aan de Amstel (nl)",
            "Oudeschild (nl)",
            "Oudesluis (nl)",
            "Oudewater (nl)",
            "Oude Wetering (nl)",
            "Oudkarspel (nl)",
            "Oudorp (nl)",
            "Oudwoude (nl)",
            "Overasselt (nl)",
            "Overberg (nl)",
            "Overdinkel (nl)",
            "Overloon (nl)",
            "Overveen (nl)",
            "Ovezande (nl)",
            "Palemig (nl)",
            "Pannerden (nl)",
            "Panningen (nl)",
            "Papekop (nl)",
            "Papendrecht (nl)",
            "Partij (nl)",
            "Paterswolde (nl)",
            "Peize (nl)",
            "Pernis (nl)",
            "Petten (nl)",
            "Philippine (nl)",
            "Piershil (nl)",
            "Pieterburen (nl)",
            "Pieterzijl (nl)",
            "Pijnacker (nl)",
            "Pingjum (nl)",
            "Plasmolen (nl)",
            "Poeldijk (nl)",
            "Poortugaal (nl)",
            "Poortvliet (nl)",
            "Posterholt (nl)",
            "Princenhof (nl)",
            "Prinsenbeek (nl)",
            "Puiflijk (nl)",
            "Purmerend (nl)",
            "Purmerland (nl)",
            "Puth (nl)",
            "Putte (nl)",
            "Putten (nl)",
            "Puttershoek (nl)",
            "Raalte (nl)",
            "Raamsdonksveer (nl)",
            "Randwijk (nl)",
            "Ravenstein (nl)",
            "Ravenswoud (nl)",
            "Reeuwijk (nl)",
            "Rekken (nl)",
            "Renesse (nl)",
            "Renkum (nl)",
            "Renswoude (nl)",
            "Ressen (nl)",
            "Retranchement (nl)",
            "Reusel (nl)",
            "Reuver (nl)",
            "Rheden (nl)",
            "Rhenen (nl)",
            "Rhenoy (nl)",
            "Rhoon (nl)",
            "Ridderkerk (nl)",
            "Riethoven (nl)",
            "Rietveld (nl)",
            "Rijckholt (nl)",
            "Rijen (nl)",
            "Rijkevoort (nl)",
            "Rijnsburg (nl)",
            "Rijpwetering (nl)",
            "Rijsbergen (nl)",
            "Rijsenhout (nl)",
            "Rijssen (nl)",
            "Rijswijk (nl)",
            "Rijswijk (nl)",
            "Rilland (nl)",
            "Rinsumageast (nl)",
            "Rips (nl)",
            "Rivierenwijk (nl)",
            "Rixtel (nl)",
            "Rockanje (nl)",
            "Roden (nl)",
            "Rodenrijs (nl)",
            "Roelofarendsveen (nl)",
            "Roermond (nl)",
            "Roggel (nl)",
            "Rolde (nl)",
            "Roodeschool (nl)",
            "Roosendaal (nl)",
            "Roosteren (nl)",
            "Rooth (nl)",
            "Rosmalen (nl)",
            "Rossum (nl)",
            "Rossum (nl)",
            "Rotterdam (nl)",
            "Rottum (nl)",
            "Rottum (nl)",
            "Rozenburg (nl)",
            "Rozenburg (nl)",
            "Rozendaal (nl)",
            "Rucphen (nl)",
            "Ruinen (nl)",
            "Ruinerwold (nl)",
            "Rutten (nl)",
            "Ruurlo (nl)",
            "s-Heerenberg (nl)",
            "Saasveld (nl)",
            "Sambeek (nl)",
            "Santpoort-Noord (nl)",
            "Sappemeer (nl)",
            "Sassenheim (nl)",
            "Sas van Gent (nl)",
            "Schagen (nl)",
            "Schagerbrug (nl)",
            "Schaijk (nl)",
            "Schalkhaar (nl)",
            "Scharmer (nl)",
            "Scheemda (nl)",
            "Schellinkhout (nl)",
            "Schermerhorn (nl)",
            "Scherpenisse (nl)",
            "Scherpenzeel (nl)",
            "Schiedam (nl)",
            "Schiermonnikoog (nl)",
            "Schijndel (nl)",
            "Schildwolde (nl)",
            "Schimmert (nl)",
            "Schinnen (nl)",
            "Schin op Geul (nl)",
            "Schinveld (nl)",
            "Schipborg (nl)",
            "Schipluiden (nl)",
            "Schoondijke (nl)",
            "Schoonebeek (nl)",
            "Schoonhoven (nl)",
            "Schoorl (nl)",
            "Schore (nl)",
            "Sellingen (nl)",
            "Serooskerke (nl)",
            "Sevenum (nl)",
            "Sibculo (nl)",
            "Siddeburen (nl)",
            "Siebengewald (nl)",
            "Silvolde (nl)",
            "Simpelveld (nl)",
            "Sint-Michielsgestel (nl)",
            "Sint-Oedenrode (nl)",
            "Sint Agatha (nl)",
            "Sint Annaland (nl)",
            "Sint Annaparochie (nl)",
            "Sint Anthonis (nl)",
            "Sint Hubert (nl)",
            "Sint Jansteen (nl)",
            "Sintjohannesga (nl)",
            "Sint Joost (nl)",
            "Sint Maarten (nl)",
            "Sint Maartensdijk (nl)",
            "Sint Nicolaasga (nl)",
            "Sint Odilienberg (nl)",
            "Sint Pancras (nl)",
            "Sint Philipsland (nl)",
            "Sint Willebrord (nl)",
            "Sittard (nl)",
            "Slagharen (nl)",
            "Sleen (nl)",
            "Sleeuwijk (nl)",
            "Slenaken (nl)",
            "Sliedrecht (nl)",
            "Slijk-Ewijk (nl)",
            "Slochteren (nl)",
            "Slootdorp (nl)",
            "Sloterdijk (nl)",
            "Sluis (nl)",
            "Sluiskil (nl)",
            "Smilde (nl)",
            "Sneek (nl)",
            "Soerendonk (nl)",
            "Soest (nl)",
            "Soesterberg (nl)",
            "Someren (nl)",
            "Sommelsdijk (nl)",
            "Son en Breugel (nl)",
            "Spaarndam (nl)",
            "Spakenburg (nl)",
            "Spanbroek (nl)",
            "Spaubeek (nl)",
            "Spierdijk (nl)",
            "Spijk (nl)",
            "Spijkenisse (nl)",
            "Sprang (nl)",
            "Sprundel (nl)",
            "Stad aan 't Haringvliet (nl)",
            "Stadskanaal (nl)",
            "Stampersgat (nl)",
            "Staphorst (nl)",
            "Stationsbuurt (nl)",
            "Stedum (nl)",
            "Steenbergen (nl)",
            "Steensel (nl)",
            "Steenwijk (nl)",
            "Steggerda (nl)",
            "Steijl (nl)",
            "Stein (nl)",
            "Stellendam (nl)",
            "Sterksel (nl)",
            "Stevensbeek (nl)",
            "Stevensweert (nl)",
            "Stiens (nl)",
            "Stolwijk (nl)",
            "Stompetoren (nl)",
            "Stompwijk (nl)",
            "Stoutenburg (nl)",
            "Strijen (nl)",
            "Strijensas (nl)",
            "Stroe (nl)",
            "Stuifzand (nl)",
            "Sumar (nl)",
            "Surhuisterveen (nl)",
            "Surhuizum (nl)",
            "Susteren (nl)",
            "Suwald (nl)",
            "Swalmen (nl)",
            "Sweikhuizen (nl)",
            "Swifterbant (nl)",
            "Taarlo (nl)",
            "Tegelen (nl)",
            "Ten Boer (nl)",
            "Ten Post (nl)",
            "Ter Aar (nl)",
            "Ter Apel (nl)",
            "Ter Apelkanaal (nl)",
            "Terblijt (nl)",
            "Terborg (nl)",
            "Terheijden (nl)",
            "Terneuzen (nl)",
            "Terschuur (nl)",
            "Teteringen (nl)",
            "The Hague (nl)",
            "Tholen (nl)",
            "Tiel (nl)",
            "Tienhoven (nl)",
            "Tienraij (nl)",
            "Tijnje (nl)",
            "Tilburg (nl)",
            "Tilligte (nl)",
            "Tinte (nl)",
            "Tjerkwerd (nl)",
            "Tolbert (nl)",
            "Toldijk (nl)",
            "Tolkamer (nl)",
            "Tricht (nl)",
            "Tubbergen (nl)",
            "Tuitjenhorn (nl)",
            "Tull (nl)",
            "Tweede Exloermond (nl)",
            "Tweede Valthermond (nl)",
            "Twello (nl)",
            "Twijzelerheide (nl)",
            "Twisk (nl)",
            "Tynaarlo (nl)",
            "Tytsjerk (nl)",
            "Tzummarum (nl)",
            "Uddel (nl)",
            "Uden (nl)",
            "Udenhout (nl)",
            "Ugchelen (nl)",
            "Uitdam (nl)",
            "Uitgeest (nl)",
            "Uithoorn (nl)",
            "Uithuizen (nl)",
            "Uithuizermeeden (nl)",
            "Uitwellingerga (nl)",
            "Ulestraten (nl)",
            "Ulft (nl)",
            "Ulicoten (nl)",
            "Ulrum (nl)",
            "Ulvenhout (nl)",
            "Ureterp (nl)",
            "Urk (nl)",
            "Urmond (nl)",
            "Ursem (nl)",
            "Utrecht (nl)",
            "Vaals (nl)",
            "Vaassen (nl)",
            "Valburg (nl)",
            "Valkenburg (nl)",
            "Valkenburg (nl)",
            "Valkenswaard (nl)",
            "Valthe (nl)",
            "Valthermond (nl)",
            "Varik (nl)",
            "Varsseveld (nl)",
            "Vasse (nl)",
            "Veen (nl)",
            "Veendam (nl)",
            "Veenendaal (nl)",
            "Veenhuizen (nl)",
            "Veenoord (nl)",
            "Veghel (nl)",
            "Velddriel (nl)",
            "Velden (nl)",
            "Veldhoven (nl)",
            "Velp (nl)",
            "Velsen (nl)",
            "Velsen-Noord (nl)",
            "Ven-Zelderheide (nl)",
            "Venhorst (nl)",
            "Venhuizen (nl)",
            "Venlo (nl)",
            "Venray (nl)",
            "Vianen (nl)",
            "Vierhouten (nl)",
            "Vierlingsbeek (nl)",
            "Vierpolders (nl)",
            "Vijfhuizen (nl)",
            "Vilt (nl)",
            "Vinkeveen (nl)",
            "Vlaardingen (nl)",
            "Vlagtwedde (nl)",
            "Vledder (nl)",
            "Vleuten (nl)",
            "Vlieland (nl)",
            "Vlijmen (nl)",
            "Vlodrop (nl)",
            "Voerendaal (nl)",
            "Vogelenzang (nl)",
            "Vogelwaarde (nl)",
            "Volendam (nl)",
            "Volkel (nl)",
            "Voorburg (nl)",
            "Voorhout (nl)",
            "Voorschoten (nl)",
            "Voorst (nl)",
            "Voorthuizen (nl)",
            "Vorden (nl)",
            "Vorstenbosch (nl)",
            "Vortum-Mullem (nl)",
            "Vragender (nl)",
            "Vreeland (nl)",
            "Vries (nl)",
            "Vriezenveen (nl)",
            "Vroomshoop (nl)",
            "Vrouwenpolder (nl)",
            "Vught (nl)",
            "Vuren (nl)",
            "Waalre (nl)",
            "Waalwijk (nl)",
            "Waardenburg (nl)",
            "Waarder (nl)",
            "Waarland (nl)",
            "Waddinxveen (nl)",
            "Wagenberg (nl)",
            "Wagenborgen (nl)",
            "Wageningen (nl)",
            "Walterswald (nl)",
            "Wamel (nl)",
            "Wanroij (nl)",
            "Wanssum (nl)",
            "Wapenveld (nl)",
            "Warder (nl)",
            "Warffum (nl)",
            "Warmenhuizen (nl)",
            "Warmond (nl)",
            "Warnsveld (nl)",
            "Waspik (nl)",
            "Wassenaar (nl)",
            "Wateringen (nl)",
            "Waterland (nl)",
            "Weerselo (nl)",
            "Weert (nl)",
            "Weesp (nl)",
            "Wehl (nl)",
            "Weidum (nl)",
            "Well (nl)",
            "Wellerlooi (nl)",
            "Wemeldinge (nl)",
            "Werkendam (nl)",
            "Werkhoven (nl)",
            "Wervershoof (nl)",
            "Wessem (nl)",
            "West-Knollendam (nl)",
            "West-Terschelling (nl)",
            "Westbeemster (nl)",
            "Westbroek (nl)",
            "Westdorpe (nl)",
            "Westerbork (nl)",
            "Westerhaar-Vriezenveensewijk (nl)",
            "Westerhoven (nl)",
            "Westervoort (nl)",
            "Westerwijtwerd (nl)",
            "Westkapelle (nl)",
            "Westmaas (nl)",
            "Westzaan (nl)",
            "Weurt (nl)",
            "Wezep (nl)",
            "Wierden (nl)",
            "Wieringerwaard (nl)",
            "Wieringerwerf (nl)",
            "Wierum (nl)",
            "Wijchen (nl)",
            "Wijckel (nl)",
            "Wijdenes (nl)",
            "Wijdewormer (nl)",
            "Wijhe (nl)",
            "Wijk aan Zee (nl)",
            "Wijk bij Duurstede (nl)",
            "Wijlre (nl)",
            "Wijnaldum (nl)",
            "Wijnandsrade (nl)",
            "Wijngaarden (nl)",
            "Wijster (nl)",
            "Wildervank (nl)",
            "Willemstad (nl)",
            "Wilnis (nl)",
            "Wilp (nl)",
            "Winkel (nl)",
            "Winschoten (nl)",
            "Winssen (nl)",
            "Winsum (nl)",
            "Wintelre (nl)",
            "Winterswijk (nl)",
            "Wissenkerke (nl)",
            "Witharen (nl)",
            "Wittem (nl)",
            "Witteveen (nl)",
            "Woensdrecht (nl)",
            "Woerden (nl)",
            "Woerdense Verlaat (nl)",
            "Wognum (nl)",
            "Wolfheze (nl)",
            "Wolphaartsdijk (nl)",
            "Woltersum (nl)",
            "Wolvega (nl)",
            "Wommels (nl)",
            "Wons (nl)",
            "Workum (nl)",
            "Wormer (nl)",
            "Wormerveer (nl)",
            "Woubrugge (nl)",
            "Woudenberg (nl)",
            "Woudrichem (nl)",
            "Woudsend (nl)",
            "Wouwsche Plantage (nl)",
            "Yde (nl)",
            "Yerseke (nl)",
            "Ysbrechtum (nl)",
            "Zaamslag (nl)",
            "Zaandam (nl)",
            "Zaandijk (nl)",
            "Zaanstad (nl)",
            "Zalk (nl)",
            "Zaltbommel (nl)",
            "Zandeweer (nl)",
            "Zandvoort (nl)",
            "Zeddam (nl)",
            "Zeeland (nl)",
            "Zeerijp (nl)",
            "Zeewolde (nl)",
            "Zeist (nl)",
            "Zelhem (nl)",
            "Zetten (nl)",
            "Zevenaar (nl)",
            "Zevenbergen (nl)",
            "Zevenbergschen Hoek (nl)",
            "Zevenhoven (nl)",
            "Zevenhuizen (nl)",
            "Zierikzee (nl)",
            "Zieuwent (nl)",
            "Zijderveld (nl)",
            "Zoetermeer (nl)",
            "Zoeterwoude (nl)",
            "Zonnemaire (nl)",
            "Zorgvlied (nl)",
            "Zoutelande (nl)",
            "Zoutkamp (nl)",
            "Zuid-Beijerland (nl)",
            "Zuid-Scharwoude (nl)",
            "Zuidbroek (nl)",
            "Zuidermeer (nl)",
            "Zuiderpark (nl)",
            "Zuidhorn (nl)",
            "Zuidland (nl)",
            "Zuidlaren (nl)",
            "Zuidoostbeemster (nl)",
            "Zuidwolde (nl)",
            "Zuidzande (nl)",
            "Zuilichem (nl)",
            "Zundert (nl)",
            "Zutphen (nl)",
            "Zwaag (nl)",
            "Zwaagdijk-Oost (nl)",
            "Zwaanshoek (nl)",
            "Zwanenburg (nl)",
            "Zwartebroek (nl)",
            "Zwartemeer (nl)",
            "Zwartewaal (nl)",
            "Zwartsluis (nl)",
            "Zwijndrecht (nl)",
            "Zwinderen (nl)",
            "Zwolle (nl)"
        ],
        'be' => [
            "Aalst (be)",
            "Aalter (be)",
            "Aarschot (be)",
            "Aartselaar (be)",
            "Affligem (be)",
            "Alken (be)",
            "Alveringem (be)",
            "Antwerpen (be)",
            "Anzegem (be)",
            "Ardooie (be)",
            "Arendonk (be)",
            "As (be)",
            "Asse (be)",
            "Assenede (be)",
            "Avelgem (be)",
            "Baarle-Hertog (be)",
            "Balen (be)",
            "Beernem (be)",
            "Beerse (be)",
            "Beersel (be)",
            "Begijnendijk (be)",
            "Bekkevoort (be)",
            "Beringen (be)",
            "Berlaar (be)",
            "Berlare (be)",
            "Bertem (be)",
            "Bever (be)",
            "Beveren (be)",
            "Bierbeek (be)",
            "Bilzen (be)",
            "Blankenberge (be)",
            "Bocholt (be)",
            "Boechout (be)",
            "Bonheiden (be)",
            "Boom (be)",
            "Boortmeerbeek (be)",
            "Borgloon (be)",
            "Bornem (be)",
            "Borsbeek (be)",
            "Boutersem (be)",
            "Brakel (be)",
            "Brasschaat (be)",
            "Brecht (be)",
            "Bredene (be)",
            "Bree (be)",
            "Brugge (be)",
            "Brussel (be)",
            "Buggenhout (be)",
            "Damme (be)",
            "De Haan (be)",
            "De Panne (be)",
            "De Pinte (be)",
            "Deerlijk (be)",
            "Deinze (be)",
            "Denderleeuw (be)",
            "Dendermonde (be)",
            "Dentergem (be)",
            "Dessel (be)",
            "Destelbergen (be)",
            "Diepenbeek (be)",
            "Diest (be)",
            "Diksmuide (be)",
            "Dilbeek (be)",
            "Dilsen-Stokkem (be)",
            "Drogenbos (be)",
            "Duffel (be)",
            "Edegem (be)",
            "Eeklo (be)",
            "Erpe-Mere (be)",
            "Essen (be)",
            "Evergem (be)",
            "Galmaarden (be)",
            "Gavere (be)",
            "Geel (be)",
            "Geetbets (be)",
            "Genk (be)",
            "Gent (be)",
            "Geraardsbergen (be)",
            "Gingelom (be)",
            "Gistel (be)",
            "Glabbeek (be)",
            "Gooik (be)",
            "Grimbergen (be)",
            "Grobbendonk (be)",
            "Haacht (be)",
            "Haaltert (be)",
            "Halen (be)",
            "Halle (be)",
            "Ham (be)",
            "Hamme (be)",
            "Hamont-Achel (be)",
            "Harelbeke (be)",
            "Hasselt (be)",
            "Hechtel-Eksel (be)",
            "Heers (be)",
            "Heist-op-den-Berg (be)",
            "Hemiksem (be)",
            "Herent (be)",
            "Herentals (be)",
            "Herenthout (be)",
            "Herk-de-Stad (be)",
            "Herne (be)",
            "Herselt (be)",
            "Herstappe (be)",
            "Herzele (be)",
            "Heusden-Zolder (be)",
            "Heuvelland (be)",
            "Hoegaarden (be)",
            "Hoeilaart (be)",
            "Hoeselt (be)",
            "Holsbeek (be)",
            "Hooglede (be)",
            "Hoogstraten (be)",
            "Horebeke (be)",
            "Houthalen-Helchteren (be)",
            "Houthulst (be)",
            "Hove (be)",
            "Huldenberg (be)",
            "Hulshout (be)",
            "Ichtegem (be)",
            "Ieper (be)",
            "Ingelmunster (be)",
            "Izegem (be)",
            "Jabbeke (be)",
            "Kalmthout (be)",
            "Kampenhout (be)",
            "Kapelle-op-den-Bos (be)",
            "Kapellen (be)",
            "Kaprijke (be)",
            "Kasterlee (be)",
            "Keerbergen (be)",
            "Kinrooi (be)",
            "Kluisbergen (be)",
            "Knokke-Heist (be)",
            "Koekelare (be)",
            "Koksijde (be)",
            "Kontich (be)",
            "Kortemark (be)",
            "Kortenaken (be)",
            "Kortenberg (be)",
            "Kortessem (be)",
            "Kortrijk (be)",
            "Kraainem (be)",
            "Kruibeke (be)",
            "Kruisem (be)",
            "Kuurne (be)",
            "Laakdal (be)",
            "Laarne (be)",
            "Lanaken (be)",
            "Landen (be)",
            "Langemark-Poelkapelle (be)",
            "Lebbeke (be)",
            "Lede (be)",
            "Ledegem (be)",
            "Lendelede (be)",
            "Lennik (be)",
            "Leopoldsburg (be)",
            "Leuven (be)",
            "Lichtervelde (be)",
            "Liedekerke (be)",
            "Lier (be)",
            "Lierde (be)",
            "Lievegem (be)",
            "Lille (be)",
            "Linkebeek (be)",
            "Lint (be)",
            "Linter (be)",
            "Lo-Reninge (be)",
            "Lochristi (be)",
            "Lokeren (be)",
            "Lommel (be)",
            "Londerzeel (be)",
            "Lubbeek (be)",
            "Lummen (be)",
            "Maarkedal (be)",
            "Maaseik (be)",
            "Maasmechelen (be)",
            "Machelen (be)",
            "Maldegem (be)",
            "Malle (be)",
            "Mechelen (be)",
            "Meerhout (be)",
            "Meise (be)",
            "Melle (be)",
            "Menen (be)",
            "Merchtem (be)",
            "Merelbeke (be)",
            "Merksplas (be)",
            "Mesen (be)",
            "Meulebeke (be)",
            "Middelkerke (be)",
            "Moerbeke (be)",
            "Mol (be)",
            "Moorslede (be)",
            "Mortsel (be)",
            "Nazareth (be)",
            "Niel (be)",
            "Nieuwerkerken (be)",
            "Nieuwpoort (be)",
            "Nijlen (be)",
            "Ninove (be)",
            "Olen (be)",
            "Oostende (be)",
            "Oosterzele (be)",
            "Oostkamp (be)",
            "Oostrozebeke (be)",
            "Opwijk (be)",
            "Oud-Heverlee (be)",
            "Oud-Turnhout (be)",
            "Oudenaarde (be)",
            "Oudenburg (be)",
            "Oudsbergen (be)",
            "Overijse (be)",
            "Peer (be)",
            "Pelt (be)",
            "Pepingen (be)",
            "Pittem (be)",
            "Poperinge (be)",
            "Putte (be)",
            "Puurs-Sint-Amands (be)",
            "Ranst (be)",
            "Ravels (be)",
            "Retie (be)",
            "Riemst (be)",
            "Rijkevorsel (be)",
            "Roeselare (be)",
            "Ronse (be)",
            "Roosdaal (be)",
            "Rotselaar (be)",
            "Ruiselede (be)",
            "Rumst (be)",
            "Schelle (be)",
            "Scherpenheuvel-Zichem (be)",
            "Schilde (be)",
            "Schoten (be)",
            "Sint-Genesius-Rode (be)",
            "Sint-Gillis-Waas (be)",
            "Sint-Katelijne-Waver (be)",
            "Sint-Laureins (be)",
            "Sint-Lievens-Houtem (be)",
            "Sint-Martens-Latem (be)",
            "Sint-Niklaas (be)",
            "Sint-Pieters-Leeuw (be)",
            "Sint-Truiden (be)",
            "Spiere-Helkijn (be)",
            "Stabroek (be)",
            "Staden (be)",
            "Steenokkerzeel (be)",
            "Stekene (be)",
            "Temse (be)",
            "Ternat (be)",
            "Tervuren (be)",
            "Tessenderlo (be)",
            "Tielt (be)",
            "Tielt-Winge (be)",
            "Tienen (be)",
            "Tongeren (be)",
            "Torhout (be)",
            "Tremelo (be)",
            "Turnhout (be)",
            "Veurne (be)",
            "Vilvoorde (be)",
            "Vleteren (be)",
            "Voeren (be)",
            "Vorselaar (be)",
            "Vosselaar (be)",
            "Waasmunster (be)",
            "Wachtebeke (be)",
            "Waregem (be)",
            "Wellen (be)",
            "Wemmel (be)",
            "Wervik (be)",
            "Westerlo (be)",
            "Wetteren (be)",
            "Wevelgem (be)",
            "Wezembeek-Oppem (be)",
            "Wichelen (be)",
            "Wielsbeke (be)",
            "Wijnegem (be)",
            "Willebroek (be)",
            "Wingene (be)",
            "Wommelgem (be)",
            "Wortegem-Petegem (be)",
            "Wuustwezel (be)",
            "Zandhoven (be)",
            "Zaventem (be)",
            "Zedelgem (be)",
            "Zele (be)",
            "Zelzate (be)",
            "Zemst (be)",
            "Zoersel (be)",
            "Zonhoven (be)",
            "Zonnebeke (be)",
            "Zottegem (be)",
            "Zoutleeuw (be)",
            "Zuienkerke (be)",
            "Zulte (be)",
            "Zutendaal (be)",
            "Zwalm (be)",
            "Zwevegem (be)",
            "Zwijndrecht (be)"
        ]
    ];

    /**
     * @param string $userRoleName
     * @param string $visibility
     * @return array|null
     */
    public static function selectableFields(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $result = [];

        if (isset(self::$selectableFields['common'][$visibility])) {
            $result = array_merge($result, self::$selectableFields['common'][$visibility]);
        }

        if (isset(self::$selectableFields[$userRoleName][$visibility])) {
            $result = array_merge($result, self::$selectableFields[$userRoleName][$visibility]);
        }

        return (empty($result)) ? null : $result;
    }

    /**
     * @param string $fieldName
     * @param string $userRoleName
     * @param string $arrayManipulationMethodName
     * @return mixed|null
     * @throws \Exception
     */
    public static function selectableField(
        string $fieldName,
        string $userRoleName = 'bot',
        string $arrayManipulationMethodName = ''
    ) {
        $data = self::getSelectableFieldData($fieldName, $userRoleName);

        if ($arrayManipulationMethodName != '') {
            $data = self::applyArrayMethod($arrayManipulationMethodName, $data);
        }

        if (!empty($data)) {
            return $data;
        }

        return null;
    }

    /**
     * @param string $userRoleName
     * @param string $visibility
     * @return array|null
     */
    public static function userTableFields(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $visibilities = ['public', 'private'];

        $result = [];

        if ($visibility == 'all') {
            foreach ($visibilities as $v) {
                if (isset(self::$userTableFields['common'][$v])) {
                    $result = array_merge($result, self::$userTableFields['common'][$v]);
                }

                if (isset(self::$userTableFields[$userRoleName][$v])) {
                    $result = array_merge($result, self::$userTableFields[$userRoleName][$v]);
                }
            }
        } else {
            if (isset(self::$userTableFields['common'][$visibility])) {
                $result = array_merge($result, self::$userTableFields['common'][$visibility]);
            }

            if (isset(self::$userTableFields[$userRoleName][$visibility])) {
                $result = array_merge($result, self::$userTableFields[$userRoleName][$visibility]);
            }
        }

        return (empty($result)) ? null : $result;
    }

    /**
     * @param string $userRoleName
     * @param string $visibility
     * @return array|null
     */
    public static function textFields(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $visibilities = ['public', 'private'];

        $result = [];

        if ($visibility == 'all') {
            foreach ($visibilities as $v) {
                if (isset(self::$textFields['common'][$v])) {
                    $result = array_merge($result, self::$textFields['common'][$v]);
                }

                if (isset(self::$textFields[$userRoleName][$v])) {
                    $result = array_merge($result, self::$textFields[$userRoleName][$v]);
                }

            }
        } else {
            if (isset(self::$textFields['common'][$visibility])) {
                $result = array_merge($result, self::$textFields['common'][$visibility]);
            }

            if (isset(self::$textFields[$userRoleName][$visibility])) {
                $result = array_merge($result, self::$textFields[$userRoleName][$visibility]);
            }
        }

        return (empty($result)) ? null : $result;
    }

    public static function textInputs(string $userRoleName = 'bot', string $visibility = 'public')
    {
        $visibilities = ['public', 'private'];

        $result = [];

        if ($visibility == 'all') {
            foreach ($visibilities as $v) {
                if (isset(self::$textInputs['common'][$v])) {
                    $result = array_merge($result, self::$textInputs['common'][$v]);
                }

                if (isset(self::$textInputs[$userRoleName][$v])) {
                    $result = array_merge($result, self::$textInputs[$userRoleName][$v]);
                }
            }
        } else {
            if (isset(self::$textInputs['common'][$visibility])) {
                $result = array_merge($result, self::$textInputs['common'][$visibility]);
            }

            if (isset(self::$textInputs[$userRoleName][$visibility])) {
                $result = array_merge($result, self::$textInputs[$userRoleName][$visibility]);
            }
        }

        return (empty($result)) ? null : $result;
    }


    /**
     * @param string $userRoleName
     * @return array
     */
    public static function publicFieldNames(string $userRoleName = 'bot')
    {
        return array_merge(
            array_keys(self::selectableFields($userRoleName, 'public')),
            array_keys(self::userTableFields($userRoleName, 'public')),
            self::textFields($userRoleName, 'public'),
            self::textInputs($userRoleName, 'public')
        );
    }

    /**
     * @param string $fieldName
     * @param string $userRoleName
     * @return mixed
     */
    private static function getSelectableFieldData(string $fieldName, string $userRoleName)
    {
        $data = [];

        if (
            isset(self::$selectableFields['common']['public']) &&
            in_array($fieldName, array_keys(self::$selectableFields['common']['public']))
        ) {
            $data = self::$selectableFields['common']['public'][$fieldName];
            return $data;
        } elseif (
            isset(self::$selectableFields[$userRoleName]['public']) &&
            in_array($fieldName, array_keys(self::$selectableFields[$userRoleName]['public']))
        ) {
            $data = self::$selectableFields['common']['public'][$fieldName];
            return $data;
        } elseif (
            isset(self::$selectableFields['common']['private']) &&
            in_array($fieldName, array_keys(self::$selectableFields['common']['private']))
        ) {
            $data = self::$selectableFields['common']['private'][$fieldName];
            return $data;
        } elseif (
            isset(self::$selectableFields[$userRoleName]['private']) &&
            in_array($fieldName, array_keys(self::$selectableFields[$userRoleName]['private']))
        ) {
            $data = self::$selectableFields[$userRoleName]['private'][$fieldName];
            return $data;
        }
        return $data;
    }

    /**
     * @param string $arrayManipulationMethodName
     * @param $data
     * @return mixed
     * @throws \Exception
     */
    private static function applyArrayMethod(string $arrayManipulationMethodName, array $data)
    {
        $allowedArrayManipulations = [
            'array_flip',
            'array_keys',
            'array_values'
        ];

        if (!in_array($arrayManipulationMethodName, $allowedArrayManipulations)) {
            throw new \Exception;
        }

        $data = call_user_func($arrayManipulationMethodName, $data);
        return $data;
    }

    /**
     * @return array
     */
    public static function getCities(string $countryCode = null, string $userCountryCode = null)
    {
        if (null === $countryCode) {
            if ($userCountryCode && $userCountryCode == 'be') {
                $allCities = array_merge(
                    self::$cities['be'],
                    self::$cities['nl']
                );
            } else {
                $allCities = array_merge(
                    self::$cities['nl'],
                    self::$cities['be']
                );

            }

            return $allCities;
        }

        return self::$cities[$countryCode];
    }
}
